const canvas = document.getElementById("gameCanvas")
const ctx = canvas.getContext("2d")

let veriDizi = ["Lehrer / öğretmen",
"Licht / ışık",
"Uhr / saat",
"Himmel / gökyüzü",
"Bibliothek / kütüphane",
"beste / en iyi",
"Ski / kayak",
"Alter / yaş",
"aufwärts / yukarı",
"Glas / cam, bardak",
"Anteil / pay, hisse",
"fähig / yetenekli, becerikli",
"zwischen / arasında, arasına",
"Katastrophe / felaket, afet",
"erforschen / araştırmak",
"Besprechung / konuşma, görüşme",
"Brot / ekmek",
"Agentur / acente",
"Bau / yapı, inşaat",
"Autofahrer / araba sürücüsü",
"Bericht / rapor, açıklama",
"Betrieb / işletme, firma",
"Bürgermeister / belediye başkanı",
"Arbeitsamt / iş ve işçi bulma kurumu",
"Amt / görev, memuriyet, makam",
"Ausmaß / boyut, ölçü",
"Abkürzung / kısaltma, kestirme yol",
"Appetit / iştah, afiyet",
"Anfrage / başvuru, müracaat, sorgulama",
"Ansprechpartner / muahatap, görüşülecek kişi",
"aussteigen / araçtan inmek",
"Brille / gözlük",
"Abschnitt / bölüm, kesim",
"ausstellen / sergilemek, düzenlemek",
"ausländisch / yabancı, yurt dışı ile ilgili",
"Anschluss / bağlantı, birleşme",
"Ausdruck / ifade, anlatım",
"Kundendienst / müşteri hizmetleri",
"Asyl / sığınma, iltica",
"Brieftasche / cüzdan",
"Lehrling / çırak",
"Gebiet / bölge, toprak, alan",
"aufhören / bitmek, sona ermek, durmak",
"Angst / korku, kaygı",
"können / yapabilmek, edebilmek",
"Ausschuss / kurul, komite",
"geehrt / sayın",
"aufräumen / temizlemek, toplamak",
"Ausländer / yabancı",
"Abend / akşam",
"einsteigen / taşıta binmek",
"fordern / istemek, talep etmek",
"Abteilung / bölüm",
"aufrichtig / dürüst, içten, samimi",
"bereit / hazır",
"Fußball / futbol",
"Bewohner / oturan, sakin",
"dagegen / ona karşı, buna karşı",
"denken / düşünmek, sanmak",
"kurz / kısa, kısa boylu",
"Kilometer / kilometre",
"Auto / araba",
"kommunal / yerel, belediye ile ilgili",
"Frühling / ilkbahar",
"kennenlernen / tanımak, tanışmak",
"Donnerstag / perşembe",
"Krankenschein / vizite kağıdı",
"Guthaben / alacak, mevduat",
"Fahrrad / bisiklet",
"Kalorie / kalori",
"daher / öyleyse, bundan dolayı",
"fehlerhaft / hatalı, kusurlu",
"Kampf / savaş, mücadele, yarışma",
"Fenster / pencere",
"Garantie / garanti",
"Ausflug / gezi",
"entführen / kaçırmak",
"knapp / dar, sıkı, kıt",
"Hersteller / üretici, imalatçı",
"derartig / bu gibi, böyle, bu tür",
"Braut / gelin, nişanlı kız",
"Landkarte / harita",
"Autor / yazar",
"Ernte / hasat, ürün",
"Kleingeld / bozuk para",
"Kreis / daire, çember, ilçe",
"ernsthaft / ciddi",
"Besitzer / sahip",
"fehlen / eksik olmak, yokluğunu hissetmek",
"benutzen / kullanmak",
"attraktiv / çekici, cazip",
"basieren / dayanmak, baz almak",
"Kreuzung / kavşak, dörtyol ağzı",
"bestätigen / doğrulamak, onaylamak",
"ausführlich / ayrıntılı, detaylı",
"kalkulieren / hesaplamak",
"gleich / eşit, aynı, şimdi, birazdan",
"Arzt / doktor",
"Leistung / performans, başarı, verim",
"Ermäßigung / indirim",
"Geräusch / gürültü",
"Herd / ocak",
"bewerten / değer biçmek, değerlendirmek",
"Krebs / yengeç, yengeç burcu, kanser",
"komisch / gülünç, komik",
"fleißig / çalışkan",
"erleben / yaşamak, görmek",
"Gedanke / düşünce, fikir",
"entkommen / kaçmak, kurtulmak",
"Brennstoff / yakıt, akaryakıt",
"Lebenslauf / özgeçmiş",
"Loch / delik, çukur",
"eklig / iğrenç",
"kochen / pişirmek, kaynatmak",
"Kapitän / kaptan",
"Krieg / savaş",
"Bestand / varlık, mevcut, stok",
"größtenteils / çoğu, büyük ölçüde",
"Körper / beden, gövde, vücut",
"Leute / insanlar, toplum, halk",
"Gegend / semt, bölge",
"Ader / damar",
"Anruf / telefon görüşmesi, çağrı",
"Bildschirm / monitör",
"Bremse / fren",
"auskommen / geçinmek",
"absichtlich / kasten, kasıtlı olarak",
"erfreulich / sevindirici",
"Gras / ot, çim, çimen",
"Fazit / sonuç",
"entfernt / uzak",
"anfangen / başlamak",
"frei / serbest, özgür, bedava",
"farbig / renkli",
"Hof / avlu",
"neidisch / kıskanç",
"Markt / pazar, market, piyasa",
"Pfeffer / karabibier",
"Null / sıfır",
"modisch / modaya uygun",
"Lage / durum, konum",
"backen / pişirmek",
"mild / yumuşak, ılımlı, hoşgörülü",
"Lizenz / lisans",
"Neujahr / yeni yıl",
"kennen / tanımak, bilmek",
"aussagen / ifade etmek, belirtmek",
"Film / film",
"ausnahmsweise / istisnai olarak, bir kerelik",
"konsequent / tutarlı, mantıklı",
"Explosion / patlama",
"medien / medya",
"Studie / inceleme, araştırma",
"Rasierapparat / traş makinesi",
"nutzlos / yararsız, boş",
"ihnen / onlara",
"Schluss / son, sonuç",
"Stewardess / hostes",
"Geschäft / iş, işyeri, dükkan",
"schlicht / basit, sade, düz",
"Angewohnheit / alışkanlık",
"aktuell / güncel",
"sauer / ekşi, kızgın, küskün",
"Bücherei / kütüphane",
"Hähnchen / kızarmış tavuk, piliç",
"nachmittags / öğleden sonra",
"ernst / ciddi, ağırbaşlı",
"Konferenz / toplantı, görüşme",
"Not / yoksulluk, sıkıntı, darlık",
"Gewürz / baharat",
"schlagen / vurmak, dövmek, yenmek",
"Stand / durum, düzey, seviye",
"Inhalt / içerik, içindeki, kapsam",
"Informatik / bilişim",
"offiziell / resmi",
"passieren / geçmek, olmak",
"mehrmals / birçok kez",
"Orchester / orkestra",
"Bekenntnis / kabul, itiraf",
"einfach / basit, kolay, sade, tek",
"reisen / seyahat etmek",
"öfter / daha sık",
"Mannschaft / takım, mürettebat",
"schuldig / suçlu, borçlu",
"Interesse / ilgi",
"Silber / gümüş",
"aufwecken / uyandırmak",
"halten / tutmak, durmak",
"Arbeitszeit / mesai saatleri",
"Gast / misafir",
"Eröffnung / açılış",
"per / ile, aracılığıyla",
"Mord / cinayet",
"großzügig / cömert, alçakgönüllü",
"Mehrheit / çoğunluk",
"Literatur / edebiyat",
"scharf / keskin, sivri, acı, sert",
"Prämie / prim, ödül",
"umfassen / kapsamak, sarılmak, kucaklamak",
"Verbraucher / tüketici",
"Bronze / bronz, tunç",
"bewusst / kasti, mahsus, bilinçli",
"Gewalt / güç, kuvvet, şiddet",
"erforderlich / gerekli",
"Versprechen / söz, vaat",
"Komma / virgül",
"häufig / sık sık, yoğun",
"chemisch / kimyasal",
"Rind / sığır",
"Oper / opera",
"Größe / boyut, büyükük, beden, ölçü",
"sanft / yumuşak, hafif, nazik",
"Sonnabend / cumartesi",
"abends / akşamleyin, akşamları",
"Abschied / ayrılma, ayrılış",
"stabil / sağlam, değişmez, sabit",
"Verletzung / sakatlık, sakatlanma",
"erfüllen / yerine getirmek",
"Schwiegervater / kayınpeder",
"Hälfte / yarısı",
"Auftrag / görev, iş emri, sipariş",
"Telefonbuch / telefon rehberi",
"stinken / kokmak, pis kokmak",
"Alkohol / alkol",
"Hund / köpek",
"Glaube / inanç, iman",
"Schiff / gemi",
"Scheidung / boşanma",
"also / böylece, o halde, o zaman",
"spät / geç",
"intellektuell / zihinsel, anlıksal, entelektüel",
"Imbiss / atıştırmalık büfe",
"Motor / motor",
"Gehirn / beyin, akıl",
"Ordnung / düzen, tertip",
"Katalog / katalog",
"eifersüchtig / kıskanç",
"benachrichtigen / haber vermek",
"Geschenk / hediye",
"regeln / düzeltmek, yoluna koymak",
"forschen / araştırmak, soruşturmak",
"spekulieren / spekülasyon yapmak",
"gefallen / hoşuna gitmek",
"Glück / şans, talih",
"brav / terbiyeli, uslu",
"global / global, küresel",
"Verstoß / ihlal",
"sorgfältig / özenli, dikkatli",
"schlank / ince, narin",
"rechts / sağda, sağa",
"Apfel / elma",
"Teufel / şeytan",
"Absender / gönderen",
"Schritt / adım",
"abbrechen / kırmak, koparmak, yarıda kesmek",
"Öffentlichkeit / kamu, halk",
"gut / iyi, güzel",
"Hunger / açlık",
"sofort / hemen, derhal",
"Verstand / akıl",
"Aprikose / kayısı",
"Aufnahme / fotoğraf veya ses kaydı",
"übertreiben / abartmak, büyütmek",
"böse / fena, kötü",
"Anmeldung / kayıt",
"Gefängnis / cezaevi, hapishane",
"sogar / bile, hatta",
"provisorisch / geçici, eğreti",
"tot / ölü, ölmüş",
"unwichtig / önemsiz",
"Unterwäsche / iç çamaşır",
"automatisch / otomatik",
"Minute / dakika",
"unschuldig / suçsuz",
"eigen / kendi, özel",
"Hitze / şiddetli sıcak",
"überzeugen / inandırmak, ikna etmek",
"prüfen / incelemek, sınamak, araştırmak",
"Nuss / fındık",
"Vermögen / varlık, servet",
"nicht / değil",
"haben / sahip olmak",
"Opfer / özveri, fedakarlık, kurban",
"Brief / mektup",
"Glühbirne / ampul",
"abgeordnete / milletvekili, parlementer",
"haften / yapışmak, sorumlu olmak",
"Hauptstadt / başkent",
"gegenwärtig / şimdiki, şu andaki",
"Teil / parça",
"Traum / rüya",
"klar / açık, berrak",
"feiern / kutlamak, tebrik etmek",
"spielen / oynamak, enstrüman çalmak",
"Geflügel / kümes hayvanı",
"damit / bununla, onunla, amacıyla",
"langsam / yavaş",
"Gewicht / ağırlık, önem",
"Bauer / çiftçi, köylü",
"Schild / işaret, levha, tabela",
"Deutschland / Almanya",
"Christ / hristiyan",
"überfüllt / tıka basa dolu",
"Briefmarke / pul",
"gesprächig / konuşkan",
"Erziehung / eğitim, yetiştirme",
"nützlich / yararlı, faydalı",
"immer / daima, her zaman",
"still / sessiz, sakin",
"generell / genel",
"telefonieren / telefon etmek",
"heute / bugün",
"kontrollieren / denetlemek, kontrol etmek",
"Ursprung / köken, kaynak",
"skeptisch / kuşkucu",
"Rücktritt / istifa",
"Öl / yağ, petrol",
"Verlust / kayıp, zarar",
"ehrlich / dürüst, doğru, namuslu",
"kräftig / güçlü, kuvvetli",
"interessant / ilginç",
"Nation / ulus, millet",
"informieren / bilgilendirmek",
"Folge / sıra, dizi, sonuç",
"Umfrage / soruşturma, anket",
"sitzen bleiben / sınıfta kalmak",
"reich / zengin",
"Stunde / saat, ders",
"Parlament / parlemento, meclis",
"Bad / banyo",
"erscheinen / görünmek",
"Gemüse / sebze",
"unbequem / rahatsız",
"Insel / ada",
"klagen / şikayet etmek, dava açmak",
"illegal / yasadışı, illegal",
"unbekannt / bilinmeyen, tanınmayan",
"seltsam / garip, acayip, tuhaf",
"sexuell / cinsel",
"hin / oraya, şuraya",
"Schwester / kız kardeş, abla, hemşire",
"Druck / basınç, baskı",
"Physik / fizik",
"identisch / aynı, özdeş",
"unterwegs / yolda",
"um / etrafında, hakkında, konusunda",
"Fläche / yüzey, alan",
"Brötchen / küçük ekmek",
"und / ve",
"kommen / gelmek",
"Bezirk / bölge, semt, mahalle",
"fließend / akıcı",
"Hemd / gömlek",
"umsteigen / taşıtla aktarma yapmak",
"Bäckerei / fırın",
"plötzlich / aniden, birdenbire, ansızın",
"südlich / güneyinde",
"Blatt / yaprak, kağıt, gazete",
"misstrauisch / kuşkulu, güvensiz",
"beschreiben / betimlemek, tarif etmek",
"Unterricht / öğretim, ders",
"regnerisch / yağmurlu",
"bunt / renkli",
"Vater / baba",
"Volk / halk, ulus",
"folgen / izlemek, takip etmek, uymak",
"Komponist / besteci",
"Gesicht / yüz",
"Kompromiss / uzlaşma",
"Finger / parmak",
"Paar / çift",
"Verkehrszeichen / trafik işareti",
"auswandern / göçmek, göç etmek",
"Stellung / durum, iş, görev",
"anrufen / telefon etmek",
"Linie / çizgi, hat",
"stündlich / her saat, saatlik, saat başı",
"Aktion / hareket, eylem, girişim",
"Volumen / hacim",
"peinlich / üzücü, utandırıcı, nahoş",
"nur / yalnız, sadece",
"Meer / deniz",
"übernehmen / üzerine almak, devir almak",
"klassisch / klasik",
"laden / yüklemek, davet etmek",
"spannend / ilginç, heyecanlı, sürükleyici",
"Reaktion / tepkime, reaksiyon",
"unklar / belirsiz, anlaşılmaz",
"Geste / el kol hareketi, jest",
"Akte / evrak, belge, dosya",
"Toast / tost",
"direkt / dolaysız, direkt",
"Feiertag / bayram günü, tatil günü",
"meinen / sanmak, düşünmek, kastetmek",
"unhöflich / kaba, nezaketsiz",
"Norden / kuzey",
"Aufzug / asansör, kılık kıyafet",
"Spedition / nakliyat, taşımacılık",
"November / kasım",
"ganz / bütün, tam, tümüyle",
"Verhältnis / ilişki, oran",
"Turm / kule",
"anmelden / haber vermek, bildirmek",
"spucken / tükürmek",
"besorgt / kaygılı, endişeli",
"Ausschnitt / kesim, bölüm, parça",
"Atmosphäre / atmosfer, hava, ortam",
"beraten / danışmak, görüşmek",
"demokratisch / demokratik",
"Grad / derece",
"Tod / ölüm",
"Gestalt / biçim, şekil, sima, şahsiyet",
"Sitzung / oturum, toplantı",
"finden / bulmak",
"markieren / işaretlemek",
"Umleitung / başka yöne çevirme, yönlendirme",
"Unternehmen / girişim, kuruluş",
"Gesprächszeit / konuşma süresi",
"unser / bizim",
"ungelesen / okunmamış",
"Unternehmer / girişimci, işveren",
"Ampel / trafik ışığı",
"finanziell / mali, parasal",
"Anzug / kostüm, elbise",
"so / böyle, şöyle, öyle",
"Topf / tencere, kap, çanak",
"unbestimmt / belli belirsiz",
"entlang / boyunca",
"Kritik / eleştiri",
"Nachmittag / öğleden sonra",
"unterzeichnen / imzalamak",
"hart / sert, katı",
"Fisch / balık",
"durch / arasından, içinden, aracılığıyla",
"gelten / geçerli olmak, geçmek, sayılmak",
"schrecklich / korkunç",
"drängen / acele etmek, itişip kakışmak",
"chatten / chat yapmak",
"Auskunft / bilgi, danışma",
"sehen / görmek, bakmak",
"trocken / kuru, kurak, çorak",
"leise / hafif, yavaş, sessiz",
"Risiko / risk",
"nun / şimdi, şu anda",
"hoffen / umut etmek, ummak",
"Türkei / Türkiye",
"beständig / sürekli, devamlı, istikrarlı",
"monatlich / aylık",
"sitzen / oturmak",
"erfolgreich / başarılı",
"ideal / ideal, mükemmel",
"Auswahl / seçenek, seçme, çeşit",
"hungrig / aç",
"lachen / gülmek",
"Humor / mizah",
"utopisch / ütopik, hayali",
"Substanz / madde, cevher, varlık",
"daneben / yanında, bunun yanısıra",
"Politik / politika",
"Arbeitnehmer / çalışan, işçi",
"Essen / yemek",
"Sprache / dil, lisan",
"kassieren / hesap almak, para almak",
"schwer / ağır, güç, zor",
"Aussicht / manzara, umut, şans",
"stechen / sokmak, batırmak",
"Moment / an",
"unverantwortlich / sorumsuz",
"drehen / çevirmek, döndürmek",
"niesen / hapşırmak",
"Unglück / felaket, facia, talihsizlik",
"gegen / karşı, yaklaşık, aşağı yukarı",
"Krankheit / hastalık",
"hierher / buraya",
"überlegen / düşünmek, üstün",
"hören / işitmek, duymak",
"einige / birkaç, biraz, bazıları",
"Sache / konu, iş, mesele",
"Regen / yağmur",
"Tennis / tenis",
"Abkommen / antlaşma, sözleşme",
"miserabel / feci, berbat, çok kötü",
"Suppe / çorba",
"schießen / ateş etmek, vurmak, gol atmak",
"teilen / bölmek",
"Lohn / ödül, ücret",
"einkaufen / satın almak, alışveriş yapmak",
"Pflaume / erik",
"lange / uzun zaman",
"Verkäufer / satıcı, tezgahtar",
"gratulieren / kutlamak, tebrik etmek",
"glänzen / parlamak",
"alphabetisch / alfabetik",
"Park / park",
"Gründer / kurucu",
"überreden / ikna etmek",
"Konto / hesap",
"Küche / mutfak",
"Unterstützung / destek, yardım",
"Übersetzung / çeviri",
"nachprüfen / gözden geçirmek, kontrol etmek",
"Obst / meyve",
"Trennung / bölme, ayırma, ayrılık",
"Tag / gün, gündüz",
"Ei / yumurta",
"tagsüber / gündüz zamanı",
"Anwendung / uygulama, kullanma",
"damals / o zaman, bir zamanlar",
"Vorteil / avantaj",
"teilnehmen / katılmak",
"Verpackung / ambalaj",
"Antrag / öneri, teklif, önerge",
"Wohnort / ikametgah",
"geschehen / olmak, vuku bulmak",
"Mitte / ortası, orta yer, merkez",
"Realschule / ortaokul",
"geheim / gizli",
"Tasche / cep, çanta",
"Schüler / öğrenci",
"Nummer / numara, sayı",
"Hilfe / yardım, imdat",
"losen / çekiliş yapmak, kura çekmek",
"Kuh / inek",
"lebendig / canlı, sağ",
"traditionell / geleneksel",
"dokumentarisch / belgesel, dokümanter",
"sportlich / sportif, sportmen",
"schließen / kapamak, bitirmek, bitmek",
"elektrisch / elektrikli, elektriksel",
"Hinweis / bilgi, not, ipucu",
"ernähren / beslemek",
"ebenfalls / aynı şekilde, aynen",
"Fußgänger / yaya",
"Auffassung / görüş, anlayış",
"verwenden / kullanmak, zaman çaba harcamak",
"Hauptbahnhof / merkez istasyon, gar",
"freilassen / serbest bırakmak",
"veröffentlichen / yayımlamak",
"lernen / öğrenmek",
"minus / eksi",
"fein / ince, zarif, hassas",
"vermeiden / kaçınmak, sakınmak",
"geradeaus / dosdoğru, dümdüz",
"Nachweis / kanıt, delil, belge",
"Landschaft / yöre, bölge, manzara",
"Foto / fotoğraf",
"gesetzlich / yasal",
"Fahrstuhl / asansör",
"verteilen / dağıtmak, paylaştırmak",
"Forderung / istek, istem, talep",
"leer / boş",
"Verlag / yayınevi",
"sicher / emin, güvenilir",
"Affe / maymun",
"Arm / kol",
"taub / sağır",
"Untersuchung / inceleme, araştırma",
"total / tam, bütün, komple",
"verlieren / kaybetmek, yitirmek",
"akzeptieren / kabul etmek",
"verursachen / neden olmak",
"manche / birçok, bazı",
"gemein / adi, bayağı, alçak",
"Vorschrift / kural, talimat",
"sagen / demek, söylemek",
"Vergangenheit / geçmiş zaman, mazi",
"Auflage / baskı, tiraj",
"Stiftung / vakıf",
"intensiv / yoğun",
"diesmal / bu kez, bu defa",
"laut / gürültülü, göre, uyarınca",
"dünn / ince, zayıf",
"Hindernis / engel",
"merkwürdig / garip, tuhaf",
"dunkel / karanlık, koyu",
"Aufsatz / yazı, makale",
"regelmäßig / düzenli",
"Funktion / fonksiyon",
"Fahrkarte / bilet",
"Gitarre / gitar",
"Liste / liste",
"seelisch / ruhsal",
"innerhalb / içinde, zarfında",
"gar / pişmiş, hiçbir şey, hiç kimse",
"Umwelt / çevre",
"Kenntnis / bilgi",
"Aufregung / heyecan",
"April / nisan",
"Fest / bayram, şenlik",
"Gelegenheit / fırsat, şans",
"Programm / program",
"bewölkt / bulutlu",
"verzichten / vazgeçmek, feragat etmek",
"Schaden / hasar, zarar",
"aber / fakat, ama",
"Sonne / güneş",
"Saison / mevsim",
"mich / beni",
"sinnlos / anlamsız, abes, saçma",
"lehren / öğretmek",
"Schatz / hazine, bitanem, canım",
"versuchen / denemek, girişmek",
"diskutieren / tartışmak",
"Dienst / hizmet, görev",
"anständig / terbiyeli, düzgün, doğru",
"Abfahrt / hareket, kalkış",
"Vorsicht / dikkat, özen, ihtiyat",
"vertrauen / güvenmek",
"farblos / renksiz",
"verfolgen / izlemek, takip etmek",
"Gewitter / fırtına",
"vollkommen / mükemmel, yetkin, kusursuz",
"Täter / suçlu, zanlı",
"Scheiße / bok",
"Achtung / dikkat",
"dick / kalın, şişman",
"stark / güçlü, kuvvetli, kalın",
"bei / yakınında, sırasında, iken",
"einladen / davet etmek",
"Argument / kanıt, delil, gerekçe",
"Haar / saç",
"dringend / acil, acele",
"Angebot / öneri, teklif",
"Speise / yemek, meze",
"unverschämt / arsız, yüzsüz, utanmaz",
"spenden / bağışlamak",
"Art / çeşit, tür, tarz",
"erwachsene / yetişkin",
"Mayonnaise / mayonez",
"intern / dahili, iç",
"schleppen / taşımak, sürümek, çekmek",
"blöd / budala, enayi, gerzek",
"feucht / yaş, nemli",
"Hotel / otel",
"schmerzen / ağrımak",
"unternehmen / girişmek, el atmak, yapmak",
"bilden / oluşturmak, biçim vermek, kurmak",
"reservieren / yer ayırtmak",
"niemals / hiçbir zaman, asla",
"Arbeiter / işçi",
"Kopf / baş, kafa",
"Milliarde / milyar",
"beißen / ısırmak",
"blass / solgun, soluk",
"eng / dar, samimi, yakın",
"rot / kırmızı",
"Recht / hak, hukuk, adalet",
"Unterhose / külot",
"Ereignis / olay",
"Arbeitslosigkeit / işsizlik",
"Leiter / yönetici, müdür",
"Kopie / kopya, suret",
"tüchtig / yetenekli, becerikli",
"Nachfolger / halef, ardıl",
"vollständig / tam, bütün, eksiksiz",
"schmal / dar, ince",
"Kaugummi / sakız",
"abstrakt / soyut",
"bekommen / almak",
"vermutlich / olası, muhtemel, varsayılan",
"Abstand / mesafe, aralık",
"hinter / arkasında",
"Englisch / ingilizce",
"Königin / kraliçe",
"Laden / dükkan",
"verbinden / bağlamak, birleştirmek",
"Produkt / ürün",
"vorher / önceden, peşinen",
"ruhig / rahat, huzurlu, sessiz",
"logisch / mantıksal",
"Dusche / duş",
"Hamburger / hamburger",
"insgesamt / toplam olarak, tamamı",
"Tante / hala, teyze, yenge",
"Ehre / namus, onur",
"Ausstattung / donanım, tesisat",
"Ansage / bildiri, duyuru",
"verdächtig / kuşkulu, şüpheli",
"Yeni / bölme, kompartıman",
"Ratgeber / danışman, rehber",
"konkret / somut",
"Uniform / üniform",
"Briefkasten / posta kutusu",
"Kleid / elbise",
"Monat / ay",
"versichern / temin etmek, garanti etmek",
"schützen / korumak, savunmak",
"loben / övmek, methetmek",
"Hintergrund / arka plan",
"Kartoffel / patates",
"Messe / fuar",
"passen / uymak, yakışmak",
"üblich / alışılmış, her zamanki",
"Idee / fikir",
"Tee / çay",
"Überblick / görünüş, insiyatif",
"Feuer / ateş, yangın",
"Eintrittskarte / giriş kartı",
"vorn / önde, ileride",
"nötig / gerekli, lüzumlu",
"erschrecken / korkutmak, korkmak, ürkmek",
"vergrößern / büyütmek, genişletmek",
"verliebt / aşık",
"erheblich / oldukça çok, büyük ölçüde",
"Bibel / incil",
"Geheimnis / sır, gizem",
"froh / mutlu, neşeli",
"sachlich / nesnel, objektif, tarafsız",
"verbessern / düzeltmek, artırmak, yükseltmek",
"beruhigen / yatıştırmak, susturmak",
"Entschuldigung / özür, af, mazeret",
"holen / almak, alıp götürmek",
"Aufführung / temsil, gösteri",
"installieren / kurmak",
"Material / materyal, gereç",
"Postkarte / kartpostal",
"vorhaben / niyetinde olmak",
"Mitarbeiter / şirket çalışanı",
"Wohnzimmer / oturma odası",
"Nachname / soyadı",
"Detail / ayrıntı, detay",
"Wochenende / hafta sonu",
"Möglichkeit / olanak, olasılık",
"atmen / nefes alıp vermek, solumak",
"wenigstens / hiç olmazsa, en azından",
"Gemeinschaft / topluluk, ortaklık, birlik",
"flüssig / akıcı, sıvı, likit",
"unbedingt / kayıtsız şartsız, kesinlikle",
"aktiv / faal, etkin, aktif",
"frech / arsız, yüzsüz, küstah",
"Wasser / su",
"Stein / taş",
"furchtbar / korkunç, dehşetli",
"Statistik / istatistik",
"Vorgang / gidişat, gelişme, süreç",
"August / ağustos",
"wechseln / değiştirmek, geçmek, para bozmak",
"Tradition / gelenek",
"begründen / gerekçe göstermek",
"Mut / cesaret, yiğitlik",
"Mann / adam, erkek, koca, eş",
"Formel / formül",
"Eindruck / izlenim, etki",
"Initiative / inisiyatif",
"sympathisch / sempatik",
"überflüssig / fazla, gereksiz, lüzumsuz",
"Perspektive / açı, perspektif",
"Ursache / neden, sebep",
"Maßnahme / önlem, tedbir",
"Shampoo / şampuan",
"etwas / biraz",
"Wolle / yün",
"Muster / örnek, numune, model",
"gesamt / bütün",
"erzählen / anlatmak",
"warm / sıcak",
"Wette / bahis, iddia",
"Feier / tören, kutlama",
"verhindern / önlemek, engel olmak",
"Popcorn / patlamış mısır",
"angenehm / hoş, sempatik",
"Modem / modem",
"vergewaltigen / tecavüz etmek",
"Investition / yatırım",
"links / sol, solda",
"Niveau / düzey, seviye",
"Polizist / polis memuru",
"Halbpension / yarım pansiyon",
"doppelt / çift, iki katlı",
"miteinander / birlikte",
"Anfang / başlangıç",
"oft / sık sık",
"erst / önce, ilk önce, ancak, daha",
"lokal / yerel, yöresel",
"Umfang / hacim, kapsam, alan",
"Welt / dünya",
"weiter / devam",
"Vorschlag / öneri, teklif",
"Grund / temel, sebep, gerekçe",
"cornflakes / mısır gevreği",
"mehr / daha çok, daha",
"Seife / sabun",
"schneiden / kesmek, doğramak",
"Theater / tiyatro",
"Durst / susama, susamış olmak",
"persönlich / kişisel, özel, şahsen",
"Kirche / kilise",
"regnen / yağmak",
"Post / posta, postane",
"Erdöl / petrol",
"selten / seyrek, nadir",
"Posteingang / gelen posta",
"verbreitet / yaygın, yayılmış",
"schwach / zayıf, güçsüz",
"übel / kötü, fena",
"Verkehr / trafik, ulaşım",
"billig / ucuz",
"Vorbereitung / hazırlık",
"insbesondere / özellikle",
"Gesetz / yasa, kanun",
"Situation / durum",
"Sahne / krema, kaymak",
"Eis / buz, dondurma",
"Botschaft / haber, mesaj, büyükelçilik",
"Internet / internet",
"Wurst / sosis, sucuk",
"medizinisch / tıbbi",
"Unterschrift / imza",
"Bruder / erkek kardeş",
"verlobte / nişanlı",
"einschließlich / dahil, içinde",
"lesen / okumak",
"Verfassung / anayasa, durum",
"Prüfung / sınav, kontrol, inceleme",
"Autobahn / otoyol",
"Hals / boğaz, gırtlak",
"Europa / Avrupa",
"Frieden / barış",
"mechanisch / mekanik",
"verstehen / anlamak, kavramak",
"Überschuss / artık, kalan, fazlalık",
"Wettkampf / yarışma",
"Anspruch / iddia, hak, beklenti",
"Bein / bacak, ayak",
"Tonne / ton, fıçı, varil",
"Gastgeber / ev sahibi",
"Erdbeben / deprem",
"einschreiben / kaydetmek, yazmak",
"unterschiedlich / farklı, değişik",
"Sommer / yaz",
"Kommissar / komiser",
"rechtzeitig / tam zamanında",
"dreckig / kirli, pis",
"Arbeit / iş, çalışma",
"weinen / ağlamak",
"geil / azgın, şehvetli, şahane",
"rasch / çabuk, hızlı",
"Geduld / sabır",
"Bestimmung / tüzük, yönetmelik",
"Verkauf / satış",
"katholisch / katolik",
"Gegenteil / zıt, aksi, ters",
"Stärke / güç, kuvvet, kalınlık",
"daten / veri, bilgi",
"Milch / süt",
"meinetwegen / benim için, benim yüzümden",
"Friedhof / mezarlık",
"Witwe / dul kadın",
"gegenseitig / karşılıklı",
"Meister / usta, üstat, şampiyon",
"Anwalt / avukat, dava vekili",
"kalt / soğuk",
"Unterhemd / fanila, atlet",
"Rat / öğüt, tavsiye",
"Feuerzeug / çakmak",
"Österreich / Avusturya",
"kraftlos / güçsüz, halsiz",
"gierig / açgözlü, obur",
"hervorragend / olağanüstü, seçkin",
"Ernährung / beslenme, besin",
"Dolmetscher / tercüman",
"bekannt / tanınmış, ünlü, bilinen",
"weiß / beyaz",
"Breite / genişlik, en, enlem",
"unlogisch / mantıksız",
"ausgeben / harcamak, dağıtmak",
"hartnäckig / inatçı",
"Kreditkarte / kredi kartı",
"perfekt / kusursuz, mükemmel, yetkin",
"Ausstellung / sergi, düzenleme",
"Entspannung / gevşeme, yumuşama, rahatlama",
"mittags / öğlenleyin",
"Reparatur / onarım, tamir",
"Gastarbeiter / yabancı işçi",
"Angriff / saldırı, hücum",
"ökonomisch / ekonomik",
"Wörterbuch / sözlük",
"ungesund / sağlığa zararlı",
"darstellen / oynamak, canlandırmak",
"gefühllos / duygusuz",
"einnahmen / gelir",
"Blick / bakış",
"Kunst / sanat",
"Sport / spor",
"Widerspruch / çelişki, itiraz",
"auffällig / göz alıcı, dikkat çeken",
"Notausgang / acil çıkış kapısı",
"greifen / yakalamak, tutmak",
"Museum / müze",
"Strecke / uzaklık, mesafe, hat, yol",
"Auge / göz",
"hinein / içine, içeriye",
"Verrat / ihanet",
"freiwillig / gönüllü, isteğe bağlı",
"Bräutigam / güvey, nişanlı erkek",
"viel / çok, birçok",
"Münze / madeni para, bozuk para",
"wann / ne zaman",
"nämlich / çünkü, ise",
"Heft / defter",
"Stimme / ses, oy",
"unpraktisch / kullanışsız",
"Ausweis / kimlik kartı",
"Einwanderer / göçmen",
"trinken / içmek",
"Phase / evre, safha",
"Taschengeld / cep harçlığı",
"niedrig / alçak, düşük",
"beleidigen / hakaret etmek",
"indirekt / dolaylı, endirekt",
"Maus / fare, sıçan",
"braun / kahvrengi, güneşten yanmış, kararmış",
"Impfung / aşı",
"auf / üstünde, üzerinde",
"ausgaben / masraflar, giderler",
"Einstellung / görüş, düşünce, işe alma",
"stattfinden / olmak, meydana gelmek",
"probieren / denemek, tadına bakmak",
"traurig / üzgün",
"Interview / röportaj",
"Speicherkarte / hafıza kartı",
"Beschluss / karar",
"Wettbewerb / yarış, rekabet",
"Enkel / torun",
"mir / bana",
"vorziehen / yeğlemek, tercih etmek",
"Tat / hareket, iş, eylem",
"Westen / batı",
"Anlass / vesile, neden, sebep",
"bauen / inşa etmek, kurmak",
"außerhalb / dışında, haricinde",
"öffnen / açmak",
"Ausland / yurt dışı",
"Kuchen / kek, pasta",
"reparieren / tamir etmek",
"stolz / gurur",
"konservativ / tutucu, muhafazakar",
"Gefahr / tehlike",
"tragen / taşımak, giymek, takmak",
"kosten / değerinde olmak, tadına bakmak",
"etwa / yaklaşık, aşağı yukarı, acaba",
"verteidigen / savunmak",
"Krankenpfleger / hastabakıcı",
"Volkswirtschaft / ekonomi, iktisat",
"Fuß / ayak",
"Million / milyon",
"dazu / buna, ona, bu amaçla",
"stoppen / durmak, durdurmak",
"fest / sağlam, sıkı, kesin",
"Tisch / masa",
"fertig / hazır, bitmiş",
"Lösung / çözüm",
"Marmelade / reçel",
"Wartezimmer / bekleme odası",
"schlafen / uyumak",
"treu / sadık, güvenilir",
"Viertel / çeyrek",
"ordnen / düzenlemek, düzeltmek",
"überholen / geçmek, sollamak",
"technisch / teknik bakımdan",
"Liebe / aşk, sevgi",
"Buchhandlung / kitabevi",
"Methode / yöntem, metot",
"Geburtstag / doğum günü",
"erreichen / erişmek, ulaşmak, yetişmek",
"Verwendung / kullanış, kullanım",
"Gefühl / duygu, his",
"Personalausweis / kimlik kartı",
"Wesen / varlık, karakter, tabiat",
"voran / önde, başta",
"Boot / sandal, kayık",
"Spur / iz",
"Idol / idol, hayranlık uyandıran kişi",
"Wirkung / etki",
"Endspiel / final",
"Gramm / gram",
"Bilanz / bilanço",
"Kälte / soğuk, soğukluk",
"Handy / cep telefonu",
"Idiot / aptal, gerizekalı",
"fröhlich / sevinçli, neşeli, şen",
"einigermaßen / bir dereceye kadar, bir ölçüde",
"Flughafen / hava alanı",
"verrückt / çılgın, deli",
"absagen / iptal etmek, gelemeyeceğini bildirmek",
"verheimlichen / gizlemek, saklamak",
"antworten / cevaplamak",
"Projekt / proje, tasarı",
"verraten / ihanet etmek, ifşa etmek, söylemek",
"lauter / tamamen, baştan aşağı",
"Industrie / endüstri, sanayi",
"Acker / tarla",
"Opposition / muhalefet, karşı çıkma",
"Pflanze / bitki",
"Lunge / akciğer",
"Wimper / kirpik",
"Passwort / parola",
"evangelisch / protestan, evangelik",
"Ministerpräsident / başbakan",
"sterben / ölmek",
"Weintraube / üzüm",
"verlassen / terk etmek, bırakmak",
"Spaß / şaka, gırgır, eğlence",
"Koffer / bavul",
"Klima / iklim",
"Ausnahme / istisna",
"Bahn / tren, demir yolu",
"tauschen / değiştirmek, değiş tokuş etmek",
"betrunken / içkili, sarhoş",
"umweltfreundlich / çevre dostu",
"bearbeiten / işlemek, üzerinde çalışmak",
"Weihnachten / Noel",
"Rücksicht / saygı",
"Küste / sahil, kıyı",
"Weltall / evren",
"Hand / el",
"Wagen / araba, vagon",
"Weise / bilge",
"besitzen / sahip olmak",
"Motorrad / motorsiklet",
"Lampe / lamba",
"hinzufügen / eklemek, ilave etmek",
"umsonst / parasız, bedava, boşuna",
"Sekunde / saniye",
"Bauch / karın",
"Wind / rüzgar",
"Mensch / insan, adam",
"Hupe / korna, klakson",
"vielmals / birçok kez, çok çok",
"brutto / brüt",
"Krimi / polisiye",
"Dreieck / üçgen",
"Vorurteil / ön yargı, peşin hüküm",
"Ausgang / çıkış",
"Fabrik / fabrika",
"stehen bleiben / durmak",
"Weg / yol",
"laufen / koşmak, akmak, yürüyerek gitmek",
"entlassen / kovmak, salıvermek, tahliye etmek",
"schwanger / hamile",
"braten / kızartmak",
"Wein / şarap",
"Forschung / araştırma",
"Kissen / yastık",
"sonnig / güneşli",
"Dorf / köy",
"besondere / özel, ayrı",
"Vorwort / önsöz",
"Presse / basın",
"Einzelhandel / perakende",
"Punkt / nokta, konu, puan",
"faul / tembel, miskin, çürük, kokmuş",
"Rücken / sırt, arka",
"Richter / yargıç, hakim",
"fahren / taşıtla gitmek",
"Nachteil / sakınca, dezavantaj",
"Tabelle / liste, çizelge, tabela",
"pommes frites / patates kızartması",
"Korrespondenz / yazışma, mektuplaşma",
"giftig / zehirli",
"Anhang / ek",
"Nebel / sis",
"kaum / ancak, güçlükle, hemen hemen hiç",
"spätestens / en geç",
"Ausführung / yapma, yerine getirme",
"anfassen / dokunmak, ellemek, tutmak",
"behaupten / ileri sürmek, söylemek",
"Klavier / piyano",
"Beifall / alkış",
"Anschrift / adres",
"Regisseur / yönetmen, rejisör",
"Ausrede / bahane, mazeret",
"Generation / nesil",
"Verlängerung / uzatma",
"verantwortlich / sorumlu",
"Direktor / müdür",
"Vertrag / sözleşme, antlaşma",
"Hose / pantolon",
"bisher / şimdiye kadar, şimdiye dek",
"warnen / uyarmak",
"vorhanden / mevcut, elde hazır",
"sozusagen / tabiri caizse, sanki, adeta",
"Wort / kelime",
"Studium / yüksek öğrenim, lisans",
"Vorstand / yönetim kurulu",
"Ablauf / akış, seyir",
"roh / pişmemiş, çiğ, ham",
"Abflug / kalkış, uçuş",
"berücksichtigen / göz önünde bulundurmak",
"beseitigen / atlatmak, bertaraf etmek",
"Geständnis / itiraf",
"vorwärts / ileri",
"Sprung / atlama, sıçrama",
"flach / düz, yassı, sığ, alçak",
"da / orada, burada, çünkü",
"Vergnügen / zevk, eğlence",
"Regenschirm / şemsiye",
"Stimmung / ruh hali, hava",
"Leben / yaşam, hayat",
"Schokolade / çikolata",
"beobachten / gözlemek, gözetlemek",
"Nachbar / komşu",
"unterscheiden / ayırt etmek, ayırmak",
"Schriftsteller / yazar",
"geistlich / dinsel, ruhani",
"Freundschaft / arkadaşlık",
"Technik / teknoloji, teknik",
"Regenmantel / yağmurluk",
"Verbrecher / suçlu",
"Umsatz / satışlar, ciro",
"Beutel / torba, kese",
"Verpflichtung / yükümlülük, görev, vazife",
"gleichfalls / aynı şekilde, keza",
"Alltag / gündelik yaşam",
"nördlich / kuzeyinde",
"anhängen / eklemek, ilave etmek, katmak",
"Schule / okul",
"Fußballspieler / futbolcu",
"modern / çağdaş, modern",
"Grundgesetz / anayasa",
"speichern / depolamak, kaydetmek",
"vermissen / özlemek, yokluğunu çekmek",
"erschöpft / yorgun, bitkin",
"egal / eşit, aynı, farksız",
"umstritten / tartışmalı",
"entscheiden / karar vermek",
"Heimat / vatan",
"Juli / temmuz",
"bald / yakında",
"Natur / doğa, tabiat",
"jedenfalls / her durumda",
"verwechseln / karıştırmak",
"artig / terbiyeli, uslu",
"echt / hakiki, sahici",
"süß / tatlı, şekerli",
"Olivenöl / zeytinyağı",
"wach / uyanık",
"klären / halletmek, çözmek",
"Rest / artık, kalan, kalıntı",
"Flasche / şişe",
"Mittag / öğle",
"gründen / kurmak",
"bedeuten / anlamına gelmek, demek",
"machen / yapmak, etmek",
"speziell / özel",
"Fähre / feribot, araba vapuru",
"gefühlvoll / duygulu, duygusal",
"fühlen / duymak, hissetmek",
"korrigieren / düzeltmek",
"Architekt / mimar",
"kaufen / satın almak",
"Samstag / cumartesi",
"glaubwürdig / inanılır, güvenilir",
"treffen / karşılaşmak, rastlamak",
"Pullover / kazak",
"ähneln / benzemek",
"ungünstig / elverişsiz, uygunsuz",
"respektlos / saygısız",
"Tischtennis / masa tenisi",
"steigern / arttırmak, yükseltmek",
"Warnung / uyarı",
"Mittagessen / öğle yemeği",
"Chaos / kaos",
"unfassbar / akıl almaz, inanılmaz",
"produktiv / verimli",
"welche / hangi",
"gelb / sarı",
"Bus / otobüs",
"Benzin / benzin",
"Baum / ağaç",
"Miete / kira",
"Philosophie / felsefe",
"Menge / miktar, nicelik, küme",
"Universität / üniversite",
"Frucht / meyve",
"Zebrastreifen / yaya geçidi",
"spontan / aniden, kendiliğinden",
"Finale / final, son",
"wässerig / sulu",
"Pfeife / düdük",
"einerseits / bir yandan",
"Verwaltung / yönetim, idare",
"Erfolg / başarı, sonuç, netice",
"führen / önderlik etmek, götürmek",
"Anweisung / emir, talimat",
"Maß / ölçü",
"ungeduldig / sabırsız",
"gehören / ait olmak",
"Sendung / gönderi, yayın",
"wild / vahşi, yabani",
"bringen / getirmek",
"Nacht / gece",
"Konflikt / uyuşmazlık, çatışma",
"Geschichte / hikaye, tarih",
"Reihe / dizi, sıra",
"präsentieren / sunmak",
"sparsam / ekonomik, tutumlu",
"vergeblich / boş, yararsız, boşuna",
"geschäftlich / ticari",
"Werk / yapıt, eser, işletme",
"Fleck / leke",
"brauchen / ihtiyacı olmak",
"Reserve / yedek",
"Bildung / oluşum, bilgi, kültür",
"Besucher / ziyaretçi, konuk",
"Schwiegermutter / kayınvalide",
"Religion / din",
"Handwerker / zanaatçı, zanaatkar",
"woher / nereden",
"Kuss / öpücük",
"Dach / çatı, dam",
"Dichter / ozan, şair, yazar",
"Gerücht / söylenti ,dedikodu",
"Tempo / tempo",
"Apfelsine / portakal",
"wozu / niye, hangi maksatla",
"unerträglich / dayanılmaz, çekilmez",
"Stufe / basamak, derece, aşama",
"Verständigung / anlaşma, uzlaşma",
"sortieren / ayırmak, ayıklamak, seçmek",
"ändern / değiştirmek",
"bequem / rahat, konforlu",
"windig / rüzgarlı",
"liegen / yatmak, uzanmak",
"Baumwolle / pamuk",
"ökologisch / ekolojik",
"Spieler / oyuncu",
"Hausschuh / terlik",
"schlimm / kötü, fena",
"Minderheit / azınlık",
"wöchentlich / haftalık, her hafta",
"freundlich / dostça, candan, içten",
"bereits / önceden, şimdiden, bile",
"Werkzeug / alet",
"Frühstück / kahvaltı",
"doch / hayır, aksine, ancak",
"gelassen / soğukkanlı, sakin",
"Gewohnheit / alışkanlık",
"Blut / kan",
"wieder / yine, tekrar",
"empfindlich / duyarlı, hassas, alıngan",
"Witz / şaka, espri",
"Pflicht / görev, ödev",
"Theorie / teori, konum",
"Pension / pansiyon, emeklilik",
"heftig / şiddetli, sert",
"rauchen / sigara tütün içmek",
"vielmehr / daha doğrusu",
"berichten / rapor vermek, bildirmek",
"Zettel / kağıt parçası, not kağıdı",
"Blume / çiçek",
"Gegenstand / şey, madde, konu, mevzu",
"Erdgeschoss / zemin katı",
"staatlich / devlete ait, resmi, ulusal",
"Ansicht / fikir, görüş, düşünce",
"Ermahnung / uyarı, öğüt",
"Feind / düşman",
"Umgebung / çevre, civar",
"Besitz / mal, servet",
"Zauber / büyü, sihir",
"Baby / bebek",
"Volleyball / voleybol",
"Feuerwehr / itfaiye",
"Bluse / bluz",
"anwenden / kullanmak, uygulamak",
"unentschlossen / kararsız, ikircikli",
"theoretisch / kuramsal, teorik",
"beteiligen / katılmak",
"kaputtgehen / bozulmak, kırılmak",
"dieser / bu",
"Zimmer / oda",
"zahlreich / pek çok, sayısız",
"Kompliment / iltifat",
"Nudel / makarna, şehriye",
"Süden / güney",
"wahrscheinlich / olası, muhtemel",
"zaubern / büyü yapmak, sihir yapmak",
"Mond / Ay",
"Kino / sinema",
"ärgerlich / kızgın",
"gesetzwidrig / yasaya aykırı, yolsuz",
"Bank / bank, sıra, banka",
"Resultat / sonuç",
"Mitternacht / gece yarısı",
"Gipfel / zirve, doruk",
"gebildet / eğitimli, kültürlü",
"leiden / acı çekmek, katlanmak",
"Buch / kitap",
"großartig / harika, mükemmel",
"soeben / az önce, demin",
"Herz / kalp, yürek, can, gönül",
"Kontinent / kıta, anakara",
"kühl / serin",
"früh / erken",
"worüber / neyin üzerinde, ne üzerine",
"Konzept / taslak, plan, konsept",
"früher / daha önce, eskiden",
"vermitteln / sağlamak, temin etmek",
"Beweis / kanıt, delil",
"schauen / bakmak",
"herzlich / içten, samimi",
"Rhythmus / ritim",
"Fernsehen / televizyon",
"Konsum / tüketim",
"hierzu / bunun hakkında, bununla ilgili",
"Information / bilgi, danışma",
"mögen / istemek, sevmek",
"wissenschaftlich / bilimsel",
"Becher / bardak, tas, kupa",
"Fortschritt / ilerleme, gelişme",
"aufmerksam / dikkatli",
"Tankstelle / benzin istasyonu",
"kein / hiç, yok",
"Fahrzeug / taşıt, araç",
"Stahl / çelik",
"bitte / lütfen, buyrun",
"schädlich / zararlı",
"sozial / sosyal",
"Löwe / aslan",
"Versuch / deneme, deney",
"Kapital / sermaye, kapital",
"einsam / yalnız, tek başına, terk edilmiş",
"Import / ithalat",
"besonders / özellikle, özel olarak",
"Gruß / selam",
"Musiker / müzisyen",
"Rechtsanwalt / avukat",
"Ding / şey",
"womit / ne ile",
"wirklich / gerçek",
"Moral / ahlak",
"günstig / uygun, elverişli",
"beginnen / başlamak",
"Inflation / enflasyon",
"Bedingung / koşul, şart",
"Alternative / alternatif",
"unsympathisch / sevimsiz",
"Erfahrung / deneyim, tecrübe",
"Bezug / kılıf",
"relativ / göreceli",
"live / yayın canlı, naklen",
"Dauer / süre, müddet",
"Summe / tutar, toplam, meblağ",
"Kilogramm / kilogram",
"Marketing / pazarlama",
"Kultur / kültür",
"hinsichtlich / bakımından, ile ilgili",
"lang / uzun, uzun boylu",
"objektiv / nesnel, tarafsız",
"leben / yaşamak, oturmak",
"Prospekt / broşür",
"sauber / temiz",
"wie / nasıl",
"praktisch / pratik",
"unmöglich / olanaksız",
"hinaus / dışarı",
"nüchtern / aç, aç karnına",
"wieviel / kaç, ne kadar",
"Präsident / başkan",
"Entwurf / plan, taslak, tasarı",
"Betrag / tutar, değer, miktar",
"Hauptstraße / ana cadde",
"Garten / bahçe",
"örtlich / yerel",
"buchstabieren / harf harf söylemek, kodlamak",
"allein / yalnız, tek başına",
"Radio / radyo",
"Ingenieur / mühendis",
"selbständig / bağımsız, serbest",
"Rezept / yemek tarifi, reçete",
"Gegenwart / günümüz, şimdiki zaman",
"fördern / desteklemek, teşvik etmek",
"Identität / kimlik, özdeşlik",
"aufheben / kaldırmak, saklamak",
"längst / çoktan, çoktan beri",
"nehmen / almak",
"Führerschein / ehliyet",
"Rennen / koşu, yarış",
"Cafe / kafe, kafeterya",
"allerseits / hepsi, herkes",
"mindestens / hiç olmazsa, en azından",
"parken / park etmek",
"Diskussion / tartışma",
"Künstler / sanatçı",
"anbieten / sunmak, önermek, teklif etmek",
"wissen / bilmek",
"Urlaub / tatil, izin",
"Schuh / ayakkabı",
"klicken / tıklamak",
"Staub / toz",
"schweigen / susmak",
"danke / teşekkürr ederim",
"Begriff / kavram, fikir",
"sparen / para biriktirmek, tasarruf etmek",
"Techniker / teknisyen, tekniker",
"einsehen / anlamak, kavramak",
"Beamter / memur",
"begegnen / karşılaşmak, rastlamak",
"undeutlich / belirsiz, karışık, okunaksız",
"beinah / az kalsın, neredeyse, hemen hemen",
"Zusammenarbeit / iş birliği",
"begabt / yetenekli",
"Zubehör / aksesuar, ek parçalar",
"ledig / bekar",
"Selbstbedienung / self servis",
"Chor / koro",
"stören / rahatsız etmek",
"entdecken / keşfetmek, ortaya çıkarmak",
"Beratung / danışma, danışmanlık",
"Benutzername / kullanıcı adı",
"aufhalten / alıkoymak, tutmak",
"Sieg / zafer, galibiyet",
"Unsinn / saçmalık, zırva",
"Veranstaltung / gösteri, tören, organizasyon",
"Apparat / alet, aygıt, telefon",
"Hauptsache / en önemli şey",
"Fahrer / sürücü",
"wichtig / önemli",
"Walnuss / ceviz",
"Papier / kağıt",
"geboren / doğuştan",
"klettern / tırmanmak",
"berühmt / tanınmış, ünlü",
"Burg / kale, hisar",
"Handtuch / havlu",
"Versicherung / sigorta, teminat",
"Tür / kapı",
"Benehmen / davranış",
"fliegen / uçmak",
"Ruhe / dinlenme, sakinlik",
"Erzeugnis / ürün",
"Spielzeug / oyuncak",
"während / sırasında, iken",
"Schiedsrichter / hakem",
"Verbindung / bağlantı, ilişki, temas",
"Freitag / cuma",
"finster / karanlık, kötü, asık suratlı",
"Beruf / meslek, iş",
"liefern / teslim etmek, tedarik etmek",
"gegenüber / karşısında",
"wovon / neden",
"Abteil / bölme, kompartıman",
"irre / şaşkın, deli",
"Mittwoch / çarşamba",
"Fahrgast / yolcu",
"beide / her ikisi, ikisi birden",
"allmählich / yavaş yavaş",
"Gabel / çatal",
"überlassen / bırakmak, terk etmek",
"langweilig / sıkıcı, monoton, tekdüze",
"dabei / yanında, yanı sıra, ayrıca",
"Witwer / dul erkek",
"negativ / olumsuz",
"begleiten / eşlik etmek",
"gefährlich / tehlikeli",
"Überweisung / havale",
"austauschen / değiştirmek, değiş tokuş etmek",
"zeichnen / çizmek",
"vor / önce, evvel, önünde",
"feststellen / saptamak, tesbit etmek",
"wahr / gerçek, doğru",
"annehmen / kabul etmek, almak, varsaymak",
"nie / hiçbir zaman, asla",
"durchfallen / başaramamak, sınavda kalmak",
"oder / veya, ya da",
"Metall / maden, metal",
"vielleicht / belki",
"darauf / bunun üzerine",
"positiv / pozitif",
"unparteiisch / tarafsız",
"Schlüsselwort / anahtar kelime",
"halb / yarım, buçuk",
"Friseur / berber, kuaför",
"Mobiltelefon / cep telefonu",
"Vorfahrt / geçiş hakkı",
"verschieden / farklı, değişik, ayrı",
"Zuname / soyadı",
"Widerstand / direnç, rezistans, direniş",
"gewinnen / kazanmak",
"scheu / çekingen, sıkılgan, utangaç",
"weh tun / acımak, ağrımak",
"wert / değer",
"Brust / göğüs, bağır, meme",
"Form / biçim, şekil, kalıp",
"blond / sarışın",
"gefangene / esir, tutsak, tutuklu",
"nebenan / yanında, bitişik",
"elektronisch / elektronik",
"Zwiebel / soğan",
"Sicherheit / emniyet, güvenlik",
"Pistole / tabanca",
"erträglich / katlanılabilir, çekilir",
"Prinzessin / prenses",
"Freund / dost, erkek arkadaş",
"Bier / bira",
"dumm / aptal",
"verwandte / akraba",
"fremd / yabancı",
"behalten / korumak, saklamak, akılda tutmak",
"Reißverschluss / fermuar",
"Sehnsucht / özlem",
"schwierig / güç, zor",
"Verband / sargı, bant",
"Gott / tanrı",
"suchen / aramak",
"Salat / salata",
"vergessen / unutmak",
"verlangen / talep etmek, istemek",
"Handschuh / eldiven",
"abgeben / vermek, teslim etmek",
"Salz / tuz",
"Partner / eş, partner, ortak",
"überhaupt / genel olarak, aslında",
"ausgeschlossen / olanaksız, imkansız",
"Chemie / kimya",
"mehrere / birçok, çeşitli",
"Zufall / raslantı, şans",
"kaputtmachen / bozmak, kırmak",
"Passagier / yolcu",
"doof / aptal, salak",
"September / eylül",
"wirtschaftlich / ekonomik",
"Unterhaltung / konuşma, söyleşi, sohbet",
"steigen / çıkmak, tırmanmak, yükselmek",
"kleben / yapıştırmak",
"rufen / seslenmek, çağırmak",
"Haut / cilt, deri",
"Reisebüro / seyahat acentası",
"Außenminister / dışişleri bakanı",
"Zusammenfassung / özet",
"wunderbar / harika, olağanüstü",
"Maschine / makine",
"Zweck / amaç",
"Weizen / buğday",
"Kaffee / kahve",
"typisch / tipik",
"neutral / tarafsız, yansız",
"Abfall / çöp, atık",
"gemeinsam / ortak, birlikte",
"Zentrum / merkez",
"noch / daha, henüz",
"Strafe / ceza",
"charakteristisch / karakteristik, tipik",
"ähnlich / benzer",
"Ehe / evlilik",
"Spitze / uç, tepe, zirve",
"heiraten / evlenmek",
"Staat / devlet",
"scheinen / parlamak, parıldamak, görünmek",
"du / sen",
"Krawatte / kravat",
"erkennen / tanımak, anlamak, algılamak",
"Restaurant / restoran",
"schnell / hızlı",
"Zugang / giriş",
"kompliziert / karışık, karmaşık",
"Gegner / rakip, hasım",
"oberflächlich / yüzeysel",
"Niederlage / yenilgi, bozgun",
"Fräulein / evlenmemiş kadın",
"Tourismus / turizm",
"Schauspieler / aktör",
"Grundstück / gayrimenkul, emlak",
"umgekehrt / tersine",
"euer / sizin",
"Satz / cümle",
"Adresse / adres",
"Sieger / galip",
"mal / kere, çarpı",
"weshalb / neden, niçin",
"unfreundlich / nezaketsiz, aksi, soğuk ve yağışlı",
"herunterladen / veri indirmek",
"Medizin / tıp",
"Szene / sahne",
"Genehmigung / onay, izin",
"geizig / cimri",
"Wüste / çöl",
"Einfahrt / araçla giriş",
"besetzt / dolu, meşgul",
"Position / durum, konum",
"vorwiegend / daha ziyade, özellikle",
"besuchen / ziyaret etmek, okula gitmek",
"Handel / ticaret, alışveriş, piyasa",
"entsetzlich / korkunç, dehşetli",
"man / insan, kişi",
"Zuhörer / dinleyici",
"sonst / yoksa, aksi takdirde",
"oben / yukarıda, üstte",
"Schach / satranç",
"bummeln / gezinmek, boş gezmek",
"Regal / raf",
"aufstehen / ayağa kalkmak",
"immerhin / ne de olsa",
"Irrtum / hata, yanlışlık",
"Kabel / kablo",
"wünschen / dilemek, arzu etmek",
"infolge / den dolayı, yüzünden",
"national / ulusal, milli",
"Konzert / konser",
"Buchstabe / harf",
"ausdrücklich / açık seçik, açıkça, özellikle",
"Klingelton / zil sesi",
"Vorsprung / avantaj",
"zeigen / göstermek, işaret etmek",
"Missbrauch / kötüye kullanma",
"Basketball / basketbol",
"bloß / çıplak, açık, yalnız, sadece",
"durchführen / icra etmek, uygulamak",
"Müll / çöp",
"Zahlung / ödeme",
"Ende / son",
"tapfer / cesur, yiğit, yürekli",
"übrigens / bu arada, sırası gelmişken",
"aushalten / dayanmak, tahammül etmek",
"Dame / bayan, hanımefendi",
"überprüfen / gözden geçirmek, denetlemek",
"Text / metin, söz",
"Teller / tabak",
"Einwohner / bir yerde oturan, sakin",
"westlich / batısında",
"Herbst / sonbahar",
"bestellen / sipariş vermek, yer ayırtmak",
"Schrift / yazı",
"glauben / inanmak, sanmak",
"Immobilien / emlak, gayrimenkul",
"Werkstatt / atölye",
"Millionär / milyoner",
"Standort / bulunulan yer, mekan, pozisyon",
"Republik / cumhuriyet",
"Genuss / zevk, haz",
"Zoo / hayvanat bahçesi",
"Amateur / amatör",
"Hauptseite / ana sayfa",
"Typ / tip, model, biçim",
"Gebrauch / kullanış, kullanma",
"Netz / ağ, şebeke",
"winken / el sallamak",
"Scherz / şaka",
"ungebildet / eğitimsiz, cahil",
"morgen / yarın",
"ergänzen / tamamlamak, eklemek, ilave etmek",
"wütend / öfkeli, kudurmuş, çılgın",
"löschen / söndürmek, silmek",
"Straßenbahn / tramvay",
"entsprechend / uygun",
"Ziel / hedef, amaç, gerek",
"Verhalten / davranış, tutum",
"Erklärung / açıklama, beyan, demeç",
"heißen / anlamına gelmek, adı olmak",
"Aufgabe / ödev, görev",
"beruflich / mesleki, meslek ile ilgili",
"ungerecht / haksız, adaletsiz",
"Durchfall / ishal",
"Zug / tren, hava akımı, yudum",
"sondern / bilakis",
"bezahlen / ödemek",
"Grundschule / ilkokul",
"Zahl / sayı",
"vertreten / temsil etmek, savunmak",
"Wald / orman",
"sorgen / bakmak, sağlamak, çözmek",
"hilflos / çaresiz, aciz",
"unterschreiben / imzalamak",
"wohin / nereye",
"Gymnasium / lise",
"anders / başka türlü",
"herrlich / harika, mükemmel, müthiş",
"Antenne / anten",
"Geist / ruh, akıl, zihin",
"schön / güzel",
"elegant / şık, zarif",
"Urkunde / belge, vesika, sertifika",
"dahinter / arkasında",
"Haushalt / hane, ev halkı",
"Fremdsprache / yabancı dil",
"Orange / portakal",
"Sänger / şarkıcı",
"schüchtern / utangaç, sıkılgan",
"fantastisch / harika, şahane, mükemmel",
"Seite / yan, kenar, sayfa",
"Gesundheit / sağlık",
"Geographie / coğrafya",
"verändern / değiştirmek, değişiklik yapmak",
"offen / açık, içten, candan",
"Demokratie / demokrasi",
"besser / daha iyi",
"Schönheit / güzellik",
"integrieren / entegre etmek",
"mündlich / sözlü, sözel",
"Schnee / kar",
"Frau / kadın, eş, hanım",
"unglaublich / inanılmaz",
"Rad / tekerlek, çark",
"Zahnarzt / diş hekimi",
"Getreide / tahıl",
"Musik / müzik",
"beliebt / sevilen, tutulan",
"Überfall / soygun, saldırı",
"fassen / tutmak, yakalamak",
"Zeuge / tanık, şahit",
"Struktur / yapı",
"Name / ad, isim",
"Mühe / emek, çaba, zahmet",
"absolut / mutlak, mutlaka, kesinlikle",
"Aktie / hisse senedi",
"original / orijinal",
"tausend / bin",
"Jeans / kot",
"für / için",
"herstellen / yapmak, üretmek",
"toll / inanılmaz, enfes, mükemmel",
"fett / şişman, yağlı",
"Verständnis / anlayış",
"reichlich / çok, bol",
"Juni / haziran",
"Teilnahme / katılma, katılım",
"Unrecht / haksızlık",
"Zigarre / puro",
"komplett / komple",
"Wachstum / gelişme, büyüme, artış",
"Absicht / niyet, amaç",
"beglaubigen / onaylamak, tasdik etmek",
"Experte / uzman, bilirkişi, eksper",
"anfangs / başlangıçta, ilkin",
"Instanz / merci",
"Politiker / politikacı",
"tun / yapmak, etmek",
"Instrument / enstrüman",
"dir / sana",
"dort / orada",
"drücken / bastırmak, sıkıştırmak",
"rasen / aşırı hızla gitmek",
"Kalbfleisch / dana eti",
"geschlossen / kapalı, özel",
"Zeitalter / çağ, devir",
"Rundfunk / radyo",
"Getränk / içecek",
"König / kral",
"hierbei / bu arada",
"sowieso / zaten, nasıl olsa",
"Symbol / simge, sembol",
"Befehl / emir",
"wer / kim",
"steuern / kullanmak, sürmek, dümen tutmak",
"hinten / arkada, geride",
"fast / hemen hemen, neredeyse",
"Vertreter / temsilci, mümessil",
"plannen / planlamak, tasarlamak",
"Erlaubnis / izin",
"Anlage / yatırım, tesisat, taslak",
"Tiefe / derinlik",
"beziehungsweise / yani, daha doğrusu",
"Papst / papa",
"abholen / gidip getirmek, almaya gelmek",
"Telefon / telefon",
"Zweifel / kuşku, şüphe",
"Lust / sevinç, istek",
"obere / üst, yüksek, yukarı",
"Gepäck / bagaj, eşya",
"Filiale / şube",
"Sorge / endişe, kaygı, merak",
"Integration / entegrasyon, bütünleşme",
"Empfehlung / tavsiye, salık",
"Strom / nehir, akıntı",
"schließlich / en sonunda, nihayet",
"Kommentar / yorum",
"beabsichtigen / amaçlamak, niyetinde olmak",
"Zeichen / işaret, simge",
"jedoch / bununla birlikte, ancak",
"füllen / doldurmak",
"wolkig / bulutlu",
"fern / uzak",
"Dienstag / salı",
"unabhängig / bağımsız",
"Schere / makas",
"Trinkgeld / bahşiş",
"Gegensatz / tezat, karşıtlık",
"Moschee / cami, mescit",
"wegen / dolayı, yüzünden",
"seitdem / o zamandan beri",
"völlig / tam, çok",
"Vorfall / olay",
"Erinnerung / hafıza, hatıra, anı",
"intelligent / zeki, akıllı",
"Reportage / röportaj",
"Nachricht / mesaj, haber",
"Bürste / fırça",
"Gelände / arazi",
"genügen / yetmek",
"meistens / genellikle, çoğunlukla",
"wirksam / etkili",
"Reis / pirinç, pilav",
"Nachthemd / gecelik",
"harmlos / zararsız, art niyetsiz",
"leeren / boşaltmak",
"beerdigen / gömmek, defnetmek",
"vernachlässigen / ihmal etmek, savsaklamak",
"immun / bağışık",
"Türkisch / türkçe",
"Holz / tahta, ahşap",
"Börse / borsa",
"produzieren / üretmek, yetiştirmek",
"Batterie / pil, batarya",
"bleiben / kalmak, durmak",
"Bewerbung / istek, başvuru",
"Fleisch / et",
"vorgestern / önceki gün",
"bekannte / tanıdık",
"Ausfahrt / çıkış, gezinti",
"Deckel / kapak",
"Eintritt / giriş",
"zusammen / birlikte, beraber",
"Haltestelle / durak",
"Gespräch / konuşma, görüşme",
"Januar / ocak ayı",
"klug / akıllı",
"hässlich / çirkin",
"Hoffnung / umut",
"schlau / kurnaz, açıkgöz",
"Figur / biçim, şekil, figür",
"Einladung / davet, çağrı",
"kriterien / kriter, ölçüt",
"heilig / kutsal",
"grüßen / selamlamak",
"Bleistift / kurşunkalem",
"Antwort / cevap",
"wonach / neye göre, neyi",
"Prozent / yüzde",
"Koran / kuran",
"Skandal / skandal",
"nachmachen / taklit etmek",
"individuell / bireysel",
"gewohnt / alışkın",
"messen / ölçmek",
"schwarz / siyah",
"Anzahl / sayı, adet",
"Freiheit / özgürlük",
"Gürtel / kemer, kuşak",
"entfernen / uzaklaşırmak, silmek, yok etmek",
"Anhänger / taraftar, yandaş, römork",
"wenig / az, birkaç",
"fallen / düşmek",
"kostbar / değerli, pahalı",
"Zoll / gümrük",
"weltweit / dünya çapında",
"Schlagzeile / başlık, manşet",
"Modell / örnek, model",
"Existenz / varoluş, varlık, geçim",
"bestimmen / belirlemek, kararlaştırmak",
"Arbeitgeber / işveren",
"Gewissen / vicdan",
"Pferd / at",
"wollen / istemek",
"Pilz / mantar",
"Klub / kulüp",
"klein / küçük",
"unterstützen / desteklemek, yardım etmek",
"Wanderung / yürüyüş, gezinti",
"blau / mavi",
"Vorschuss / avans",
"Oktober / ekim",
"mitbringen / yanında getirmek",
"Mieter / kiracı",
"Missverständnis / yanlış anlama",
"Grab / mezar, gömüt, türbe",
"vorübergehend / gelip geçici",
"Übung / alıştırma, pratik",
"vermieten / kiraya vermek",
"heiter / neşeli, açık hava",
"gehen / gitmek, yürümek",
"Verfahren / yöntem, dava, yargılama",
"Lager / kamp, depo",
"Reform / reform, yenilik",
"Nichte / yeğen",
"Hebel / kaldıraç, kol",
"wohnen / oturmak",
"Montag / pazartesi",
"Bevölkerung / nüfus, ahali",
"scheitern / başarısız olmak",
"innen / içinde",
"kritisieren / eleştirmek",
"langfristig / uzun süreli",
"hier / burada",
"Übertragung / yayınlama, nakletme",
"wofür / ne için, niye",
"Anzeige / duyuru, ilan, ihbar",
"Jagd / av, avcılık",
"Berg / dağ",
"Waffe / silah",
"köstlich / nefis, lezzetli",
"Belastung / yük, ağırlık, yük olma",
"Beschäftigung / uğraş, iş",
"bremsen / fren yapmak",
"ständig / sürekli, devamlı",
"denn / ki, çünkü, zira",
"eventuell / muhtemel, olan",
"Unterschied / fark, ayrım",
"zufrieden / memnun, hoşnut",
"Ausbildung / eğitim, öğrenim",
"wahnsinnig / deli, çılgın, manyak",
"bestimmt / belirli, kesinlikle, mutlaka",
"Verspätung / gecikme",
"Raum / yer, oda, uzay, boşluk",
"passiv / pasif, edilgen",
"ziehen / çekmek, sürüklemek",
"Wirtschaft / ekonomi",
"Tanz / dans",
"Ausweg / çıkış, çare, çıkar yol",
"Parkplatz / park yeri",
"erhöhen / yükseltmek",
"küssen / öpmek",
"herab / aşağıya",
"prost / şerefe",
"Gedicht / şiir",
"Stuhl / sandalye",
"Mittelpunkt / orta, merkez",
"grau / gri",
"Zeile / satır",
"Mai / mayıs",
"Schwierigkeit / zorluk, güçlük",
"warten / beklemek",
"Problem / problem",
"irgendwo / herhangi bir yerde",
"herunter / aşağıya",
"liter / litre",
"mangelhaft / kusurlu, eksik",
"willkommen / hoş geldiniz",
"ordentlich / düzenli, düzgün, namuslu",
"Wahl / seçim",
"Wetter / hava",
"senden / göndermek, yollamak, yayınlamak",
"selbstverständlich / elbette, kuşkusuz",
"Versammlung / toplantı",
"Fach / göz, çekmece, uzmanlık alanı",
"verständlich / anlaşılır, açık",
"nichts / hiçbir şey",
"Bühne / sahne",
"Bewegung / hareket, devinim",
"nachträglich / sonradan, ek olarak",
"Mauer / duvar",
"aufpassen / dikkat etmek, göz kulak olmak",
"recht / uygun, doğru, oldukça, epey",
"spazieren gehen / dolaşmak, gezmek",
"Stelle / yer, konum, iş yeri, görev",
"Schlafanzug / pijama",
"Gerüst / iskele, çatı",
"Olive / zeytin",
"Akzent / vurgu, şive, aksan",
"Gruppe / grup",
"niemand / hiç kimse",
"normal / normal, olağan",
"Einsatz / hareket, kullanma, görevlendirme",
"Erde / yeryüzü, dünya",
"drohen / tehdit etmek",
"geeignet / uygun",
"Stoff / madde, kumaş, konu",
"sicherlich / kuşkusuz, muhakkak",
"Fußboden / döşeme, yer",
"Winter / kış",
"zugleich / aynı anda, birlikte",
"multikulturell / çok kültürlü",
"Gebäude / bina, yapı",
"Gedächtnis / hafıza",
"legen / yatırmak, koymak",
"Apotheke / eczane",
"Wand / duvar",
"merken / farkına varmak",
"Gericht / mahkeme, yemek",
"Ankunft / varış",
"Geschmack / tat",
"Erbe / mirasçı",
"Notarzt / nöbetçi doktor",
"Webseite / internet sitesi",
"erschießen / vurarak öldürmek",
"Krankenhaus / hastane",
"schenken / hediye etmek, vermek",
"Experiment / deney",
"nebenkosten / ek giderler",
"überleben / sağ kurtulmak, hayatta kalmak",
"verhältnismäßig / nisbeten",
"Frage / soru",
"Saft / özsu, meyve suyu",
"zurückgeben / geri vermek",
"Taschentuch / mendil",
"politisch / politik",
"Wunsch / dilek, istek",
"übrig / arta kalan, geriye kalan",
"Termin / kararlaştırlıan zaman, randevu",
"befriedigen / memnun etmek",
"Titel / ünvan, başlık",
"vorzüglich / mükemmel, enfes",
"tanzen / dans etmek",
"mächtig / güçlü",
"Unfall / kaza",
"massiv / yekpare, ağır, kaba",
"zählen / saymak",
"aufeinander / üst üste",
"zusammenfassen / özetlemek",
"Aussage / söz, ifade",
"Soße / sos",
"sollen / gerekli olmak",
"täglich / günlük, gündelik, her gün",
"schaffen / yaratmak, yerine getirmek",
"Roman / roman",
"schlecht / kötü",
"Praxis / pratik, uygulama, büro",
"Anfänger / acemi, yeni başlayan",
"inzwischen / bu arada",
"Jugend / gençlik",
"satt / tok, doymuş",
"außergewöhnlich / olağandışı, fevkalade",
"analysieren / analiz etmek",
"Haselnuss / fındık",
"Mutter / anne, ana",
"kaputt / bozuk, kırık",
"Taxi / taksi",
"korrekt / doğru, yanlışsız",
"schwimmen / yüzmek",
"Feld / tarla, alan",
"Meter / metre",
"nachts / geceleyin",
"Eigentum / mal, mülk",
"gespannt / meraklı",
"sprechen / konuşmak",
"irgendwohin / herhangi bir yere",
"Halle / hol, salon, lobi",
"effizient / etkili",
"Bahnhof / istasyon",
"bar / nakit, peşin",
"Prinzip / ilke, prensip",
"Pfanne / tava",
"sämtlich / bütün, bilimum, hepsi",
"Geschlecht / cinsiyet",
"Gaststätte / lokanta",
"Bitte / rica, istek",
"draußen / açıkta, dışarıda",
"Familie / aile",
"Nachfrage / talep, rağbet",
"psychologisch / psikolojik",
"falsch / yanlış, ters, sahte",
"Bekleidung / giyim",
"je / hiç",
"Gebühr / ücret",
"Prozess / dava, süreç",
"Serie / dizi, seri",
"Zigarette / sigara",
"See / deniz",
"lügen / yalan söylemek",
"Bedienung / servis, işletme, kullanım",
"Regierung / hükümet",
"Geruch / koku",
"Soldat / asker, er",
"statt / yerine",
"Gleis / ray, peron",
"Hausfrau / ev kadını",
"müde / yorgun",
"amüsant / eğlendirici, eğlenceli",
"zuversichtlich / temkinli",
"manchmal / bazen, kimi zaman",
"kulturell / kültürel",
"heiß / sıcak",
"Rätsel / bilmece, bulmaca",
"Überraschung / sürpriz",
"zärtlich / sevecen, şefkatli",
"ablehnen / reddetmek",
"Gewehr / tüfek",
"zuviel / çok fazla",
"Wecker / çalar saat",
"jung / genç",
"später / daha sonra",
"vorhin / demin, az önce",
"Rückseite / arka taraf",
"Kunststoff / plastik",
"zahlen / ödemek",
"verkaufen / satmak",
"Rose / gül",
"unfähig / yetersiz, yeteneksiz",
"hallo / alo, merhaba",
"Thema / konu",
"Kompetenz / yetki",
"Grenze / sınır",
"angenommen / varsayılan, diyelim ki",
"Rekord / rekor",
"sehr / çok, pek",
"Traube / üzüm, salkım",
"Gerät / alet, cihaz",
"dauernd / sürekli olarak",
"Ohr / kulak",
"unbewusst / bilinçsiz, şuursuz",
"anerkennen / tanımak, kabul etmek",
"vertraulich / senli benli, samimi, gizli",
"Zucker / şeker",
"Niere / böbrek",
"Visum / vize",
"natürlich / tabi, elbette",
"vernünftig / akıllı, makul, akla yatkın",
"tragbar / taşınır, portatif",
"Ball / top, balo",
"Firma / firma, şirket",
"Training / antrenman, çalışma",
"undankbar / nankör",
"bezüglich / hakkında, ilişkin",
"verheiratet / evli",
"heimlich / gizli, saklı",
"ehemalig / eski, önceki",
"Krankenschwester / hemşire",
"Mörder / katil, cani",
"Messer / bıçak",
"Sand / kum",
"Würstchen / sosis",
"Eigenschaft / nitelik, özellik",
"streichen / sürmek, boya sürmek",
"tanken / benzin almak",
"Platz / yer, alan, saha, meydan",
"zollfrei / gümrüksüz",
"Verbot / yasak",
"kurzfristig / kısa süreli",
"Zeitung / gazet",
"achten / saygı göstermek, dikkat etmek",
"Woche / hafta",
"möglich / mümkün, olası",
"Meldung / haber, rapor",
"materiell / maddi",
"genießen / tadını çıkarmak",
"eigentlich / gerçek, asıl, aslında",
"dienen / hizmet etmek, yararlı olmak",
"ungefähr / yaklaşık olarak, tahminen",
"Meinung / düşünce, görüş",
"enorm / kocaman, muazzam, harika",
"Gewerbe / meslek, sanat",
"Gleichgewicht / denge",
"Bart / sakal",
"unmittelbar / dolaysız, direkt, hemen",
"erneut / yeniden",
"Ware / mal, eşya",
"Vitamin / vitamin",
"Fladenbrot / pide",
"repräsentieren / temsil etmek",
"Ermittlung / soruşturma",
"jenseits / öte yanda, karşıda",
"lustig / gülünç, eğlendirici",
"Ufer / kıyı, sahil, kenar",
"Lied / şarkı",
"mitten / ortasında",
"hell / aydınlık, parlak, açık renk",
"aufgehen / açılmak, ufukta yükselmek, doğmak",
"Finanzminister / maliye bakanı",
"Nase / burun",
"Großmutter / büyükanne, nine",
"öffentlich / kamusal",
"endlich / sonunda, nihayet",
"kostenlos / ücretsiz, bedava",
"Geburtsort / doğum yeri",
"Protest / protesto, itiraz",
"Verein / dernek, cemiyet, kulüp",
"abrechnen / hesaplaşmak, hesap sormak",
"minderjährig / reşit olmayan",
"Versand / gönderme, sevkiyat",
"unerfahren / deneyimsiz, acemi",
"Millimeter / milimetre",
"Dose / kutu",
"geben / vermek",
"abhängig / bağlı, bağımlı",
"Mitteilung / bildiri, mesaj, haber",
"Schicksal / yazgı, talih, kader",
"Sozialhilfe / sosyal yardım",
"östlich / doğusunda",
"lieben / sevmek",
"abmachen / anlaşmak, kararlaştırmak",
"Straße / sokak, yol, cadde",
"Bescheinigung / belge, makbuz",
"alt / eski, yaşlı",
"pünktlich / dakik, tam vaktinde",
"Betrüger / dolandırıcı, üçkağıtçı",
"Löffel / kaşık",
"Bemühung / gayret, çaba",
"Zeit / zaman, süre",
"Versöhnung / barışma, mutabakat, gönül alma",
"schief / eğri, çarpık, yanlış, ters",
"Zuschauer / seyirci",
"Zusammenstoß / çarpışma",
"Gleichheit / eşitlik",
"Mitglied / üye, dernek mensubu",
"ausgezeichnet / mükemmel, olağanüstü, enfes",
"darum / onun için, o yüzden",
"senkrecht / dikey",
"wachsen / büyümek, gelişmek",
"akademisch / akademik",
"setzen / oturtmak",
"Formular / form",
"lächeln / gülümsemek",
"streng / sert, şiddetli",
"Zukunft / gelecek",
"Journalist / gazeteci",
"Beitrag / katılma, aidat",
"begrüßen / selamlamak",
"Minister / bakan",
"kritisch / kritik, eleştirel",
"Mittel / çare, yol, imkan",
"nennen / adlandırmak, söylemek",
"Bewusstsein / bilinç, şuur",
"Hausmeister / kapıcı",
"überall / her yerde, her tarafta",
"gesund / sağlıklı",
"zumachen / kapatmak",
"zunächst / ilk önce",
"Taste / tuş",
"durchschnittlich / ortalama",
"Notebook / dizüstü bilgisayar",
"Leidenschaft / tutku, hırs",
"mitmachen / katılmak",
"März / mart",
"Reise / yolculuk, seyahat",
"entschlossen / azimli, kararlı",
"krank / hasta, rahatsız",
"ununterbrochen / kesintisiz, aralıksız",
"jemand / biris, bir kims",
"Vase / vazo",
"Gewerkschaft / sendika",
"zuvor / daha önce, önceden",
"durchsetzen / kabul ettirmek, gerçekleştirmek",
"Gesellschaft / toplum, ortaklık, şirket",
"Vetter / kuzen",
"vergleichen / karşılaştırmak",
"Software / yazılım",
"dann / sonra, ondan sonra, o halde",
"bestehen / var olmak, geçmek, başarmak",
"Kredit / kredi",
"Demonstration / gösteri, protesto",
"Kraft / güç, kuvvet, enerji",
"Nähe / yakın, yakınlık",
"Kongress / kurultay, kongre",
"groß / büyük, kocaman, uzun boylu",
"Jahreszeit / mevsim",
"lieb / sevgili, sevimli, hoş",
"Bekanntschaft / tanışıklık",
"treten / tekmelemek, basmak, çiğnemek",
"Export / ihracat",
"zerstören / yıkmak, yok etmek",
"Rolle / tomar, rulo, rol",
"Preis / fiyat, ödül",
"Geld / para",
"Medikament / ilaç",
"Endstation / son durak",
"Hörer / dinleyici, ahize",
"Zuschlag / ek ücret, ücret farkı",
"vorerst / şimdilik",
"Wunder / mucize",
"Epidemie / salgın hastalık, epidemi",
"blitzen / parlamak, resim çekmek, şimşek çakmak",
"Streit / tartışma, anlaşmazlık, kavga",
"Partei / parti",
"zwar / gerçi, her ne kadar",
"Jacke / ceket, mont",
"gelingen / başarmak",
"Freude / sevinç, memnuniyet",
"bedrohen / tehdit etmek",
"nächste / en yakın, bir dahaki, ertesi",
"Fahrschein / bilet",
"Möbel / mobilya",
"sensibel / duyarlı, hassas",
"Fehler / hata, yanlışlık, kusur",
"verpassen / kaçırmak",
"beherrschen / hakim olmak, hükmetmek",
"extrem / aşırı",
"Zusammenhang / ilişki, bağlantı",
"Gurke / salatalık",
"grün / yeşil",
"Farbe / renk, boya",
"Hausaufgabe / ev ödevi",
"zweifellos / kuşkusuz",
"eigenartig / tuhaf, acayip, garip",
"Gold / altın",
"abfahren / hareket etmek, kalkmak",
"Katze / kedi",
"vorig / önceki, geçen",
"angesehen / saygın",
"Jahr / sene",
"lebensmittel / yiyecek maddeleri",
"Morgen / sabah",
"bekanntmachen / bildirmek, duyurmak",
"verboten / yasak",
"zurückkommen / dönmek, geri gelmek",
"bevorzugen / seçmek, tercih etmek",
"Entfernung / uzaklık, mesefa",
"höchstens / en çok, en fazla",
"Butter / tereyağı",
"Kurs / kurs, rota, kur",
"genug / yeter, yeterli",
"plus / artı",
"Runde / tur, topluluk, çevre",
"Freizeit / boş zaman",
"Pass / pasaport, geçit, pas",
"Respekt / saygı",
"Eingang / giriş, antre",
"voll / dolu",
"Rechnung / hesap, işlem",
"Station / istasyon, bölüm, koğuş",
"hängen / asmak, asılı durmak",
"extra / özel, ayrı, ayrıca",
"weich / yumuşak",
"Plan / plan",
"fragen / sormak",
"Stern / yıldız",
"Fußballspiel / futbol maçı",
"klopfen / vurmak",
"Ort / yer, yerleşim merkezi",
"Ostern / paskalya",
"Verfügung / emir, karar, hüküm",
"helfen / yardım etmek",
"erinnern / hatırlamak",
"Vorwurf / sitem",
"Polizei / polis",
"Auswirkung / etki, sonuç",
"unwahrscheinlich / muhtemelen olmayan",
"Insekt / böcek",
"Land / ülke, kara, toprak",
"Rock / etek",
"Richtung / yön",
"zerreißen / yırtmak, parçalamak",
"Kalender / takvim",
"nackt / çıplak",
"Onkel / amca, dayı",
"Karotte / havuç",
"Wolke / bulut",
"anstatt / yerine",
"Zustimmung / onay, rıza",
"null / sıfır",
"Kühlschrank / buzdolabı",
"Versorgung / bakma, bakım",
"süchtig / bağımlı, müptela",
"Luft / hava",
"Talent / yetenek",
"Kandidat / aday",
"was / ne",
"Kindergarten / anaokulu, yuva",
"organisieren / organize etmek",
"Fingernagel / tırnak",
"Vormittag / öğleden önce, sabah",
"geistig / zihinsel",
"aufladen / şarj etmek, doldurmak, yüklemek",
"sinnvoll / akıllıca, makul, anlam dolu",
"dich / seni",
"historisch / tarihsel",
"legal / yasal",
"zittern / titremek",
"Beispiel / örnek",
"Kommunikation / iletişim",
"gerecht / adil, dürüst",
"andererseits / öte yandan, diğer yandan",
"getrennt / ayrı ayrı",
"zumindest / hiç olmazsa, bari, en azından",
"Hochschule / yüksekokul",
"Karriere / kariyer",
"Zeichnung / çizim",
"Bettler / dilenci",
"angeblich / sözde, sanki, güya",
"zweifelhaft / kuşkulu, şüpheli",
"Papierkorb / çöp kutusu",
"vermuten / sanmak, tahmin etmek, ummak",
"über / üstünde, üzerinde",
"Zustand / durum",
"Mund / ağız",
"Einzelheit / ayrıntı",
"Kirsche / kiraz",
"explodieren / patlamak",
"Rand / kenar",
"Versehen / yanlışlık, hata",
"allgemein / genel",
"Keller / kiler, bodrum",
"erledigt / bitmiş, yorgun, perişan",
"tauchen / dalmak",
"nahezu / neredeyse, hemen hemen",
"packen / yakalamak, paketlemek, doldurmak",
"dahin / oraya",
"Toleranz / hoşgörü, tolerans",
"dafür / onun için, bunun için",
"gucken / bakmak",
"denkbar / akla yatkın gelebilen",
"Person / kişi, şahıs",
"andere / başka, diğer",
"Produktion / üretim, imalat",
"Krankenwagen / cankurtaran, ambulans",
"neu / yeni",
"schon / çoktan, bile, artık",
"Tourist / turist",
"zusammenkommen / toplanmak, buluşmak",
"unregelmäßig / düzensiz",
"Fahrt / gidiş, yolculuk",
"Beziehung / ilişki, bağlantı",
"Kennwort / şifre",
"Teppich / halı",
"notwendig / gerekli, zaruri",
"sowie / bunun gibi, ayrıca",
"Pause / ara, teneffüs",
"verbrauchen / tüketmek, kullanmak, harcamak",
"reichen / uzatmak, vermek, yetmek",
"Vorbild / örnek, model",
"Chirurgie / cerrahi",
"Kunde / müşteri",
"allerdings / kuşkusuz, elbette",
"Verzeihung / affetme, bağışlama",
"Postleitzahl / posta kodu",
"auf Wiedersehen / görüşmek üzere",
"gewiss / emin, kuşkusuz, elbette",
"Kassette / kaset, küçük kutu",
"dicht / sık, yoğun",
"Entscheidung / karar",
"herum / etrafında, çevresinde, civarında",
"leicht / hafif, kolay",
"sich / kendi, birbiri",
"Urteil / yargı, hüküm, kanı",
"Banane / muz",
"mittels / ile, yardımıyla, aracılığıyla",
"Chance / şans, fırsat",
"Hauptschule / ilköğretim okulu",
"Mädchen / kız",
"verschwenderisch / savurgan, müsrif",
"Flugzeug / uçak",
"neulich / geçenlerde",
"waagerecht / yatay",
"Dokument / belge, evrak",
"gewissenlos / vicdansız",
"Währung / para birimi",
"verunglücken / kaza geçirmek",
"Popmusik / pop müzik",
"jahrelang / yıllarca",
"maximal / azami, maksimum",
"Staatsanwalt / savcı",
"ausreichend / yeterli, yeterince",
"Bedarf / ihtiyaç, gereksinim",
"prächtig / görkemli, gösterişli",
"sichtbar / görünür, açık, belli",
"Wohnung / konut, mesken, ev",
"intim / sıkı fıkı, samimi",
"schmutzig / kirli, pis",
"Pflege / bakım",
"christlich / hristiyan",
"dennoch / buna rağmen, yine de",
"locker / gevşek, yumuşak",
"Euro / avro",
"Militär / asker, ordu",
"Fortsetzung / devam",
"ja / evet",
"jahrlich / yıllık",
"Stadion / stadyum",
"Startseite / giriş sayfası",
"Länge / uzunluk, boylam",
"tragisch / acıklı, trajik",
"Erdbeere / çilek",
"regieren / hükmetmek, hakim olmak",
"ankommen / varmak, ulaşmak",
"Ersatz / yedek, bedel, tazminat",
"Zeitschrift / dergi",
"Chef / başkan, şef, patron",
"euch / size",
"Diplom / diploma",
"Hausarzt / aile doktoru",
"anschließend / arkasından, ondan sonra",
"Bedeutung / anlam, önem",
"Verantwortung / sorumluluk",
"privat / özel, kişisel",
"Kamera / fotoğraf makinesi, kamera",
"Kanal / kanalizasyon, kanal",
"mit / ile, yardımıyla",
"Auflösung / çözülme, çözüm",
"verbringen / vakit geçirmek",
"hoffentlich / umarım",
"Datum / tarih",
"tief / derin, alçak",
"schreiben / yazmak",
"pessimistisch / kötümser",
"Begeisterung / şevk, istek, coşku",
"Sessel / koltuk",
"werfen / atmak, fırlatmak",
"menschlich / insanca, insancıl",
"Computer / bilgisayar",
"deutlich / açık, anlaşılır",
"voraus / önde, ileride, önceden",
"ewig / sonsuz, ebedi, ezeli",
"zerbrechen / kırmak",
"Pfand / rehin, depozito",
"Kontrolle / denetim, kontrol",
"Flüchtling / mülteci, sığınmacı",
"hinterher / arkasından, peşinden, sonrasında",
"zuverlässig / güvenilir, emin",
"Stadt / şehir",
"ausgehen / dışarı çıkmak, tükenmek, sönmek",
"mitnehmen / yanına almak, alıp götürmek",
"tätig / faal, çalışan, işleyen",
"Schlafzimmer / yatak odası",
"minderwertig / kalitesiz, adi",
"Zins / faiz",
"Tochter / kız evlat",
"Fanatiker / bağnaz, fanatik",
"gewöhnlich / alışılagelmiş, sıradan",
"Wäsche / yıkama, çamaşır",
"Kerze / mum",
"Behörde / resmi daire",
"Umzug / alay, kortej, taşınma, göç",
"zuletzt / sonunda, nihayet",
"erwerben / edinmek, elde etmek, kazanmak",
"Rede / konuşma, söylev",
"deshalb / bu yüzden, bundan dolayı",
"Sportler / sporcu",
"tatsächlich / gerçek, asıl",
"Kapitel / bölüm, kısım",
"naiv / saf, bön",
"mitteilen / bildirmek, haber vermek",
"gemäß / göre, uyarınca, uygun",
"Konsulat / konsolosluk",
"nervös / sinirli",
"Energie / enerji",
"reden / konuşmak, söylemek",
"nein / hayır",
"Verhandlung / görüşme, pazarlık, hukuki duruşma",
"erkälten / üşütmek, soğuk almak",
"Stipendium / burs",
"zunehmen / artmak, çoğalmak, şişmanlamak",
"Spiel / oyun",
"glücklich / şanslı, mutlu",
"Höhe / yükseklik, tepe",
"Zitrone / limon",
"verschwinden / ortadan kaybolmak, yok olmak",
"Protokoll / protokol, tutanak",
"nochmals / bir kere daha, yeniden",
"nass / ıslak",
"Haus / ev",
"Besuch / ziyaret",
"Schwein / domuz",
"gering / az, küçük, önemsiz",
"Kellner / garson",
"Semester / sömestr",
"Hafen / liman",
"Vorname / isim",
"rückwärts / geriye",
"arbeitslos / işsiz",
"anwesend / hazır, mevcut",
"islamisch / islami",
"Dutzend / düzine",
"Diebstahl / hırsızlık",
"investieren / para yatırmak, zaman harcamak",
"Herr / bay, bey",
"Hochzeit / düğün",
"Ertrag / kazanç, verim, ürün",
"Schmerz / ağrı, sancı, üzüntü",
"unnötig / gereksiz",
"unsicher / emin olmayan, kuşkulu",
"Kamm / tarak",
"Baustelle / şantiye, inşaat",
"höflich / nazik, kibar",
"breit / geniş",
"Branche / branş, şube, dal",
"weitergehen / sürmek, devam etmek",
"neugierig / meraklı",
"üben / alıştırma yapmak, egzersiz yapmak",
"orange / turuncu, kavuniçi",
"Kollege / meslektaş, iş arkadaşı",
"Party / parti",
"irgendein / herhangi bir",
"Charakter / karakter, nitelik",
"verweigern / reddetmek, kaçınmak, çekinmek",
"zuhören / dinlemek",
"grausam / acımasız",
"Husten / öksürük",
"Dieb / hırsız",
"arbeiten / çalışmak, iş yapmak",
"zuständig / ilgili, yetkili, sorumlu",
"Bereich / bölge, alan, dal, bölüm",
"nett / güzel, sevimli, nazik",
"gemütlich / rahat, sıcacık, iyi huylu, hoş",
"Osten / doğu",
"aufmachen / açmak",
"auch / de da, hatta",
"gestern / dün",
"Planet / gezegen",
"Pfirsich / şeftali",
"dauern / sürmek, devam etmek",
"optimistisch / iyimser",
"genehmigen / onaylamak, izin vermek",
"außerdem / bundan başka, ayrıca",
"Bedenken / düşünce, kuşku, şüphe",
"zurücktreten / geri çekilmek, istifa etmek",
"auswendig / ezbere",
"schlaflos / uykusuz",
"gründlich / esaslı, ayrıntılı, özenli",
"Komödie / güldürü, komedi",
"hierfür / bunun için",
"genau / tam, kesin, doğru, ayrıntılı",
"Großvater / büyükbaba, dede",
"Sonntag / pazar",
"Koalition / koalisyon",
"angaben / beyan, ifade, bilgi",
"zurück / geri, dönüş",
"erzeugen / üretmek, yapmak",
"Kategorie / kategori",
"Entwicklung / gelişim, kalkınma",
"Schrank / dolap",
"Pokal / kupa",
"richtig / doğru",
"auswählen / seçmek",
"Temperatur / ısı, sıcaklık, hararet",
"Beileid / baş sağlığı, taziye",
"auslachen / alay etmek",
"rund / yuvarlak, yaklaşık, aşağı yukarı",
"Elefant / fil",
"Stück / tane, adet, parça",
"Kosmetik / kozmetik",
"Käse / peynir",
"Trainer / antrenör",
"Saal / salon",
"Tasse / fincan",
"müssen / zorunda olmak",
"Patient / hasta",
"hoch / yüksek, yüce",
"Treppe / merdiven",
"Eltern / ebeveyn",
"Pinsel / fırça",
"riesig / devasa, muazzam",
"weg / gitmiş, yok",
"zustimmen / uygun görmek, onaylamak",
"irgendwann / herhangi bir zaman",
"verwitwet / dul",
"Empfänger / alıcı",
"Scheck / çek",
"joghurt / yoğurt",
"anzünden / yakmak, tutuşturmak",
"Vogel / kuş",
"erziehen / yetiştirmek, eğitmek",
"hinunter / aşağıya",
"Ecke / köşe, köşe başı",
"Wissenschaft / bilim",
"ziemlich / oldukça, epey",
"Sprechstunde / görüşme saati",
"international / uluslararası",
"singen / şarkı söylemek",
"erwarten / beklemek",
"Vortrag / konferans, konuşma",
"eröffnen / açmak",
"Entzündung / iltihap",
"Kind / çocuk, evlat",
"Karte / kart, bilet, oyun kağıdı",
"Schloss / kilit, saray, şato",
"ungültig / geçersiz",
"Schlüssel / anahtar",
"aufwachen / uyanmak",
"Zentralheizung / merkezi ısıtma",
"Kasse / kasa, vezne, gişe",
"Bett / yatak",
"Wahrheit / gerçek",
"Junge / oğlan, erkek çocuk",
"warum / neden, niçin",
"Klasse / sınıf",
"Spezialist / uzman",
"Büro / büro",
"ermuntern / cesaretlendirmek",
"Bankrott / iflas",
"heutzutage / günümüzde",
"Supermarkt / süpermarket",
"Streik / grev",
"Sponsor / sponsor",
"Kugelschreiber / tükenmez kalem",
"durcheinander / karmakarışık",
"zeitweise / bazen, ara sıra",
"zusätzlich / ek olarak, ilaveten",
"hinauf / yukarı",
"Transport / taşıma, nakil",
"Spielplatz / çocuklar için oyun alanı",
"Volksschule / ilkokul",
"hübsch / güzel, şirin, hoş",
"Tier / hayvan",
"äußerst / son derece, olağanüstü",
"Bild / resim",
"eintragen / yazmak, kaydetmek",
"Kontakt / temas, dokunma, kontak",
"kürzlich / geçenlerde, kısa süre önce",
"Vollmacht / yetki, vekaletname",
"jetzt / şimdi",
"rechnen / hesaplamak, saymak",
"weit / geniş, büyük, uzak",
"Sohn / oğul",
"angestelle / ücretli, memur, çalışan",
"Spiegel / ayna",
"Auswanderer / göçmen",
"Toilette / tuvalet",
"Zahn / diş",
"Tomate / domates",
"Voraussetzung / koşul, şart",
"befriedigend / memnuniyet verici",
"künstlich / yapay, suni",
"Stil / üslup, biçem, stil",
"Sekretärin / bayan sekreter",
"pro / başına, beher",
"Fall / düşme, durum, hadise",
"Mikrophon / mikrofon"]

var kayitVeri = localStorage.getItem("almancaVeri2")
let diziSira = kayitVeri || 0
let harfSira = 0
let solUstKelime = ""
canvas.width = window.innerWidth
canvas.height = window.innerHeight
const ballRadius = 15
let ballX = canvas.width / 2
let ballY = canvas.height / 2
const joystick = document.getElementById("joystick")
const joystickInner = document.getElementById("joystickInner")
let isMoving = false
let currentOffsetX = 0
let currentOffsetY = 0
let firstName = veriDizi[diziSira].split(" / ")[0].split("")
let anlamKelime = veriDizi[diziSira].split(" / ")[1]
let blueBalls = []

function drawName(name) {
    ctx.fillStyle = "black"
    ctx.font = "bold 24px Arial"
    ctx.textAlign = "left"
    ctx.letterSpacing = "2px"
    ctx.textBaseline = "top"
    ctx.fillText(name, 10, 10)
}
function drawAnlam(anlam) {
    ctx.fillStyle = "#18181a"
    ctx.font = "bold 24px Arial"
    ctx.textAlign = "left"
    ctx.textBaseline = "top"
    ctx.fillText(anlam, 10, 40)
}

function drawName2(name2) {
    ctx.fillStyle = "white"
    ctx.font = "bold 24px Arial"
    ctx.textAlign = "left"
    ctx.textBaseline = "top"   
    ctx.fillText(name2, 10, 10)
}

function anlikKelime(veri) {
    ctx.fillStyle = "white"
    ctx.font = "bold 24px Arial"
    ctx.textAlign = "left"
    ctx.textBaseline = "top"  
    ctx.fillText(veri, 10, canvas.height - 50)
}

function createBlueBalls() {
    const radius = 30
    const positions = new Set()

    firstName.forEach((letter) => {
        let x, y
        let validPosition = false

        while (!validPosition) {
            x = Math.random() * (canvas.width / 1.1 - radius * 2) + radius
            y = Math.random() * (canvas.height / 1.25 - radius * 2) + radius

            validPosition = true
            for (const ball of blueBalls) {
                const distanceToBallCenter = Math.sqrt((ball.x - x) ** 2 + (ball.y - y) ** 2)
                if (distanceToBallCenter < ball.radius + radius) {
                    validPosition = false
                    break
                }
            }
        }
        blueBalls.push({
            x: x,
            y: y,
            letter: letter,
            radius: radius,
        })
    })
}

joystick.addEventListener('touchstart', (event) => {
    isMoving = true
    event.preventDefault()
})

document.addEventListener('touchend', () => {
    isMoving = false
    joystickInner.style.transform = 'translate(0, 0)'
})

joystick.addEventListener('mousedown', (event) => {
    isMoving = true
})

document.addEventListener('mouseup', () => {
    isMoving = false
    joystickInner.style.transform = 'translate(0, 0)'
})

function draw() {
    ctx.clearRect(0, 0, canvas.width, canvas.height)
    drawBlueBalls()
    drawBall()
    drawName(veriDizi[diziSira].split(" / ")[0])
    drawAnlam(anlamKelime)
    drawName2(solUstKelime)
    anlikKelime("2700 / " + (Number(diziSira)+1))
    moveBall(currentOffsetX, currentOffsetY)
    requestAnimationFrame(draw)
}

function drawBall() {
    ctx.beginPath()
    ctx.arc(ballX, ballY, ballRadius, 0, Math.PI * 2)
    ctx.fillStyle = "white"
    ctx.fill()
    ctx.closePath()
}

function drawBlueBalls() {
    blueBalls.forEach(ball => {
        ctx.beginPath()
        ctx.arc(ball.x, ball.y, ball.radius, 0, Math.PI * 2)
        ctx.fillStyle = "#242627"
        ctx.fill()
        ctx.closePath()
        ctx.fillStyle = "white"
        ctx.font = "bold 24px Arial"
        ctx.textAlign = "center"
        ctx.textBaseline = "middle"
        ctx.fillText(ball.letter, ball.x, ball.y)
    })
}

joystick.addEventListener('touchmove', (event) => {
    if (isMoving) {
        const rect = joystick.getBoundingClientRect()
        const touch = event.touches[0]
        const offsetX = touch.clientX - (rect.left + rect.width / 2)
        const offsetY = touch.clientY - (rect.top + rect.height / 2)
        const distance = Math.sqrt(offsetX * offsetX + offsetY * offsetY)
        
        if (distance > (rect.width / 2)) { 
            const angle = Math.atan2(offsetY, offsetX)
            currentOffsetX = Math.cos(angle) * (rect.width / 2)
            currentOffsetY = Math.sin(angle) * (rect.height / 2)
        } else {
            currentOffsetX = offsetX
            currentOffsetY = offsetY
        }

        moveBall(currentOffsetX, currentOffsetY)
        joystickInner.style.transform = `translate(${currentOffsetX}px, ${currentOffsetY}px)`
    }
})

document.addEventListener('mousemove', (event) => {
    if (isMoving) { 
        const rect = joystick.getBoundingClientRect()
        const offsetX = event.clientX - (rect.left + rect.width / 2)
        const offsetY = event.clientY - (rect.top + rect.height / 2)
        const distance = Math.sqrt(offsetX * offsetX + offsetY * offsetY)
        if (distance > (rect.width / 2)) { 
            const angle = Math.atan2(offsetY, offsetX)
            currentOffsetX = Math.cos(angle) * (rect.width / 2)
            currentOffsetY = Math.sin(angle) * (rect.height / 2)
        } else {
            currentOffsetX = offsetX
            currentOffsetY = offsetY
        }
        moveBall(currentOffsetX, currentOffsetY)
        joystickInner.style.transform = `translate(${currentOffsetX}px, ${currentOffsetY}px)`
    } else if(isMoving && joystick.contains(event.target)) { 
       moveBall(currentOffsetX, currentOffsetY)     
   }
})

function moveBall(offsetX, offsetY) {
    if(isMoving){
        ballX += offsetX * 0.05
        if (ballX + ballRadius > canvas.width) ballX = canvas.width - ballRadius
        if (ballX - ballRadius < 0) ballX = ballRadius
        ballY += offsetY * 0.05
        if (ballY + ballRadius > canvas.height) ballY = canvas.height - ballRadius
        if (ballY - ballRadius < 0) ballY = ballRadius
        checkCollision()
    } 
}

function checkCollision() {
    blueBalls.forEach(ball => { 
        const distanceToBallCenter = Math.sqrt((ball.x - ballX) ** 2 + (ball.y - ballY) ** 2);    
        if (distanceToBallCenter < ball.radius + ballRadius) { 
            if (ball.letter == firstName[harfSira]) {
                solUstKelime += firstName[harfSira]
                blueBalls.splice(blueBalls.indexOf(ball), 1)
                harfSira++                
                if(harfSira == firstName.length && diziSira+1 != veriDizi.length  && window.location.host == "yapaygezegen.com"){                   
                    blueBalls = []
                    diziSira++
                    localStorage.setItem("almancaVeri2",Number(diziSira))
                    firstName = veriDizi[diziSira].split(" / ")[0].split("")
                    anlamKelime = veriDizi[diziSira].split(" / ")[1]
                    harfSira = 0
                    solUstKelime = ""
                    createBlueBalls()
                }
                if (harfSira == firstName.length && diziSira+1 ==veriDizi.length) {
                    setTimeout(() => {                       
                        blueBalls = []
                        diziSira = 0
                        localStorage.setItem("almancaVeri2",Number(diziSira))
                        firstName = veriDizi[diziSira].split(" / ")[0].split("")
                        anlamKelime = veriDizi[diziSira].split(" / ")[1]
                        harfSira = 0
                        solUstKelime = ""
                        createBlueBalls()
                    }, 5000);
                }
                return
            }   
        }
    })
}
createBlueBalls()
draw()

window.addEventListener('resize', function() {
    canvas.width = window.innerWidth
    canvas.height = window.innerHeight
    ballX = canvas.width / 2
    ballY = canvas.height / 2
})